### ISSUE TITLE
Unable to install this package

### ISSUE THREAD

**Issue by bguruprasad** [requests/requests-kerberos#109]
Hi, I am not able install this package. I run `sudo pip install requests_kerberos` and I am getting this error. It will be really great if someone could help me out with this. Thanks in advance.

Python Version : 2.7.12

```
guru@guru-esds:~$ sudo pip install requests_kerberos
.
.
Installing collected packages: pykerberos, requests-kerberos
  Running setup.py install for pykerberos ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-l6ceYu/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-YxrVzk-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'kerberos' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/kerberos.c -o build/temp.linux-x86_64-2.7/src/kerberos.o
    In file included from src/kerberos.c:19:0:
    src/kerberosbasic.h:17:27: fatal error: gssapi/gssapi.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-l6ceYu/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-YxrVzk-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-l6ceYu/pykerberos/
```
Can someone help me out?

**Comment by jborean93** [comment]
Looks like you don't have the gssapi extensions installed, you can try and run this before installing with pip

```
# for Debian/Ubuntu/etc:
$ sudo apt-get install gcc python-dev libkrb5-dev
$ pip install pywinrm[kerberos]

# for RHEL/CentOS/etc:
$ sudo yum install gcc python-devel krb5-devel krb5-workstation python-devel
$ pip install pywinrm[kerberos]
```

This will install the headers that are required by pykerberos to work.

**Comment by pupseba** [comment]
Hi,

With a Fedora 28 freshly installed, I can't install that pywinrm[kerberos] even after making sure the quoted  packages are installed (gcc python-devel krb5-devel krb5-workstation python-devel). Any idea what could be happening?

This is the error output:
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c src/kerberos.c -o build/temp.linux-x86_64-2.7/src/kerberos.o -DGSSAPI_EXT
  annobin: kerberos.c: Error: plugin built for compiler version (8.0.1) but run with compiler version (8.1.1)
  cc1: error: fail to initialize plugin /usr/lib/gcc/x86_64-redhat-linux/8/plugin/annobin.so
  cc1: error: ‘-fcf-protection=full’ requires Intel CET support. Use -mcet or both of -mibt and -mshstk options to enable CET
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pykerberos
  Running setup.py clean for pykerberos
Failed to build pykerberos
Installing collected packages: pykerberos, requests-kerberos
  Running setup.py install for pykerberos ... error
    Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-S4rY8c/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-8GUiDb/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'kerberos' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c src/kerberos.c -o build/temp.linux-x86_64-2.7/src/kerberos.o -DGSSAPI_EXT
    annobin: kerberos.c: Error: plugin built for compiler version (8.0.1) but run with compiler version (8.1.1)
    cc1: error: fail to initialize plugin /usr/lib/gcc/x86_64-redhat-linux/8/plugin/annobin.so
    cc1: error: ‘-fcf-protection=full’ requires Intel CET support. Use -mcet or both of -mibt and -mshstk options to enable CET
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-S4rY8c/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-8GUiDb/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-S4rY8c/pykerberos/

**Comment by Evidlo** [comment]
Same issue, but with `ipdb`.

**Comment by bradwilliamson** [comment]
I was looking into moving off CredSSP to Kerberos.  I'm running Fedora on my Workstation & RHEL server side off jenkins slaves. I am having the same error.  Even after installing those dependencies. 


[bradst0r@localhost ~]$ sudo yum install gcc python-devel krb5-devel krb5-workstation python-devel
Last metadata expiration check: 0:15:44 ago on Wed 20 Feb 2019 08:30:05 AM CST.
Package gcc-8.0.1-0.20.fc28.x86_64 is already installed, skipping.
Package python2-devel-2.7.15-4.fc28.x86_64 is already installed, skipping.
Package krb5-devel-1.16.1-25.fc28.x86_64 is already installed, skipping.
Package krb5-workstation-1.16.1-25.fc28.x86_64 is already installed, skipping.
Package python2-devel-2.7.15-4.fc28.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

pip install pywinrm[kerberos]
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: pywinrm[kerberos] in /usr/lib/python2.7/site-packages (0.3.0)
Requirement already satisfied: xmltodict in /usr/lib/python2.7/site-packages (from pywinrm[kerberos]) (0.11.0)
Requirement already satisfied: requests>=2.9.1 in /usr/lib/python2.7/site-packages (from pywinrm[kerberos]) (2.19.1)
Requirement already satisfied: requests-ntlm>=0.3.0 in /usr/lib/python2.7/site-packages (from pywinrm[kerberos]) (1.1.0)
Requirement already satisfied: six in /usr/lib/python2.7/site-packages (from pywinrm[kerberos]) (1.11.0)
Collecting requests-kerberos>=0.10.0; extra == "kerberos" (from pywinrm[kerberos])
  Using cached https://files.pythonhosted.org/packages/ee/a2/866f2b9a60f75055137b9ad127033e397963b2c4769d4b5fab1c3c7e8be3/requests_kerberos-0.12.0-py2.py3-none-any.whl
Requirement already satisfied: idna<2.8,>=2.5 in /usr/lib/python2.7/site-packages (from requests>=2.9.1->pywinrm[kerberos]) (2.5)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests>=2.9.1->pywinrm[kerberos]) (3.0.4)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests>=2.9.1->pywinrm[kerberos]) (1.23)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests>=2.9.1->pywinrm[kerberos]) (2018.8.24)
Requirement already satisfied: ntlm-auth>=1.0.2 in /usr/lib/python2.7/site-packages (from requests-ntlm>=0.3.0->pywinrm[kerberos]) (1.2.0)
Requirement already satisfied: cryptography>=1.3 in /usr/lib64/python2.7/site-packages (from requests-ntlm>=0.3.0->pywinrm[kerberos]) (2.3)
Collecting pykerberos<2.0.0,>=1.1.8; sys_platform != "win32" (from requests-kerberos>=0.10.0; extra == "kerberos"->pywinrm[kerberos])
  Using cached https://files.pythonhosted.org/packages/9a/b8/1ec56b6fa8a2e2a81420bd3d90e70b59fc83f6b857fb2c2c37accddc8be3/pykerberos-1.2.1.tar.gz
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/lib/python2.7/site-packages (from cryptography>=1.3->requests-ntlm>=0.3.0->pywinrm[kerberos]) (0.24.0)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in /usr/lib64/python2.7/site-packages (from cryptography>=1.3->requests-ntlm>=0.3.0->pywinrm[kerberos]) (1.11.5)
Requirement already satisfied: enum34 in /usr/lib/python2.7/site-packages (from cryptography>=1.3->requests-ntlm>=0.3.0->pywinrm[kerberos]) (1.1.6)
Requirement already satisfied: ipaddress in /usr/lib/python2.7/site-packages (from cryptography>=1.3->requests-ntlm>=0.3.0->pywinrm[kerberos]) (1.0.18)
Requirement already satisfied: pycparser in /usr/lib/python2.7/site-packages (from cffi!=1.11.3,>=1.7->cryptography>=1.3->requests-ntlm>=0.3.0->pywinrm[kerberos]) (2.14)
Installing collected packages: pykerberos, requests-kerberos
  Running setup.py install for pykerberos ... error
    Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xRPIDU/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-4qEh_C/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'kerberos' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c src/kerberos.c -o build/temp.linux-x86_64-2.7/src/kerberos.o -DGSSAPI_EXT
    cc1: error: ‘-fcf-protection=full’ requires Intel CET support. Use -mcet or both of -mibt and -mshstk options to enable CET
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xRPIDU/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-4qEh_C/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-xRPIDU/pykerberos/

**Comment by diegonayalazo** [comment]
same problem here.
ERROR: running install
    running build
    running build_ext
    building 'kerberos' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/opt/stackstorm/virtualenvs/ansible/include/python3.6m -c src/kerberos.c -o build/temp.linux-x86_64-3.6/src/kerberos.o
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by Ninroot** [comment]
Make sure to use the right version of python-devel. `yum install python3-devel` for python 3 on CentOS for example. https://stackoverflow.com/a/21530768/6244121

**Comment by glree2000** [comment]
> yum install python3-devel
This fixed the issue

**Comment by mkbond777** [comment]
> Looks like you don't have the gssapi extensions installed, you can try and run this before installing with pip
> 
> ```
> # for Debian/Ubuntu/etc:
> $ sudo apt-get install gcc python-dev libkrb5-dev
> $ pip install pywinrm[kerberos]
> 
> # for RHEL/CentOS/etc:
> $ sudo yum install gcc python-devel krb5-devel krb5-workstation python-devel
> $ pip install pywinrm[kerberos]
> ```
> 
> This will install the headers that are required by pykerberos to work.

For centos and python 3 below command worked for me:
udo yum install gcc python3-devel krb5-devel krb5-workstation python3-devel

**Comment by jborean93** [comment]
Closing as this was due to a lack of krb5 headers.

**Comment by sathhh** [comment]
Unable to run ansible-playbook after installed ansible-core. Can anyone help out.

[root@Ans-D-AS2-354145 ~]# pip3 install ansible-core
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: ansible-core in ./.local/lib/python3.6/site-packages (2.11.7)
Requirement already satisfied: jinja2 in ./.local/lib/python3.6/site-packages (from ansible-core) (3.0.3)
Requirement already satisfied: PyYAML in ./.local/lib/python3.6/site-packages (from ansible-core) (6.0)
Requirement already satisfied: cryptography in ./.local/lib/python3.6/site-packages (from ansible-core) (39.0.0)
Requirement already satisfied: packaging in ./.local/lib/python3.6/site-packages (from ansible-core) (21.3)
Requirement already satisfied: resolvelib<0.6.0,>=0.5.3 in ./.local/lib/python3.6/site-packages (from ansible-core) (0.5.4)
Requirement already satisfied: cffi>=1.12 in ./.local/lib/python3.6/site-packages (from cryptography->ansible-core) (1.15.1)
Requirement already satisfied: MarkupSafe>=2.0 in ./.local/lib/python3.6/site-packages (from jinja2->ansible-core) (2.0.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./.local/lib/python3.6/site-packages (from packaging->ansible-core) (3.0.9)
Requirement already satisfied: pycparser in ./.local/lib/python3.6/site-packages (from cffi>=1.12->cryptography->ansible-core) (2.21)

[root@Ans-D-AS2-354145 ~]# ansible --version
-bash: ansible: command not found
