### ISSUE TITLE
Manually specifying principal is not working in my scenario

### ISSUE THREAD

**Issue by mdufrasne** [requests/requests-kerberos#111]
I am attempting to make a request against a Windows Authentication secured IIS server. Windows Authentication uses the domain controller to authenticate requests first using Kerberos then NTLM should Kerberos fail.

The code is running on a Linux machine where I am logged in as a domain user (e.g matt@dopeafcompany.com)

If I run

`AUTH = HTTPKerberosAuth(mutual_authentication=REQUIRED, force_preemptive=True)`
There is no issue - all works correctly.

However, if I try to run

```
AUTH = HTTPKerberosAuth(mutual_authentication=REQUIRED,
       force_preemptive=True, principal='bob@dopeafcompany.com:bobspw')
```

Then I get an unauthorized response.

Does anyone know what I might be doing wrong?

**Comment by behackett** [comment]
I'm guessing you meant you're getting an unauthorized response? Can you post the traceback you get? I'd like to see the error message from WinKerberos.

**Comment by mdufrasne** [comment]
Yes - unauthorized :-P

Here's the traceback --  Seems to indicate something about cache collection.
FWIW, the same code works on Windows.

```
Traceback (most recent call last):
  File "example_odata_kerb_credentials.py", line 32, in <module>
    RESP = SESSION.get(URL)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 421, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 359, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 291, in prepare
    self.prepare_auth(auth, url)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 470, in prepare_auth
    r = auth(self)
  File "/usr/local/lib/python2.7/dist-packages/requests_kerberos/kerberos_.py", line 308, in __call__
    auth_header = self.generate_request_header(None, host, is_preemptive=True)
  File "/usr/local/lib/python2.7/dist-packages/requests_kerberos/kerberos_.py", line 148, in generate_request_header
    raise KerberosExchangeError("%s failed: %s" % (kerb_stage, str(error.args)))
requests_kerberos.exceptions.KerberosExchangeError: authGSSClientInit() failed: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ("Can't find client principal bob@dopeafcompany.com:bobspassword in cache collection", -1765328243))

```

**Comment by mdufrasne** [comment]
So if I kinit for bob@dopeafcompany.com - then it works -- only if I remove the password from the python script. (the : and everything after)
I also had to make the casing consistent.
Is there no way to do this without having to kinit before?

**Comment by behackett** [comment]
Oh, I see. It works on Windows with WinKerberos, just not on Linux with PyKerberos. I think I can explain. WinKerberos uses Microsoft's SSPI, which is tightly integrated with Microsoft's entire authentication stack. There is no kinit or anything like it on Windows. The credentials for the process owner are used by default, or to authenticate a different user you use the principal option with a password.

On Linux the underlying technology is MIT krb5, which uses kinit to acquire ticket granting tickets for one or more users. You have to call kinit there first.

**Comment by mdufrasne** [comment]
Makes sense - thanks - closing.
