### ISSUE TITLE
SPNEGO support 

### ISSUE THREAD

**Issue by pu239ppy** [requests/requests-kerberos#116]
Currently I need to be able to specify SPNEGO OID to a remote end point I have submitted #115 and also  there is #89 to accomplish this goal.  Any chance that any of these could be merged?

**Comment by jborean93** [comment]
@pu239ppy is there a reason why you cannot move across to https://github.com/pythongssapi/requests-gssapi or if that feature is not there, add a PR. requests-kerberos uses an older library for the krb5 integration and it probably isn't the best thing to add more features to an implementation that relies on this older code.

**Comment by pu239ppy** [comment]
@jborean93 thank you, I will give that a try.

**Comment by pu239ppy** [comment]
python-gssapi does not include SPNEGO support, so I cannot select it as a mech
https://github.com/pythongssapi/python-gssapi/issues/50
However I may have found a workaround regardless, will close this and #115 if it works

**Comment by jborean93** [comment]
I can second that, I've used the raw python-gssapi library to work with SPNEGO token with success. It would just require requests-gssapi to expose the functionality to specify the mech to use.

**Comment by pu239ppy** [comment]
The original issue was due to a very pedantic configuration on a web server where it expected a SPNEGO OID where as requests-kerberos and requests-gssapi sends a Kerberos OID.  This was easy enough to fix in requests kerberos as kerberos supports SPNEGO Authentication where as the gssapi module does not.  Regardless, this has since been fixed and this issue along with accompanying PR is no longer required

**Comment by pu239ppy** [comment]
I would add one more thing: since it seems to be the desire of the project maintainers to unwind this project, please do the following.  Mark it as `deprecated` or `maintenance` in the README.md and in fact create a master branch that includes nothing but README.md which states that this project is in maintenance and will not accept/review new pull requests or issues and that users should migrate to requests-gssapi
