### ISSUE TITLE
load krb5.conf

### ISSUE THREAD

**Issue by spartakos87** [requests/requests-kerberos#119]
Hi! I want to take a token from rest api which use kerberos . My question is how to load to request_kerberos the info of krb5.conf which already have...any idea?

**Comment by sigmavirus24** [comment]
This is better suited to [StackOverflow](https://stackoverflow.com) I think. That said, it's helpful if we know what you've already tried. I don't believe this library or any of its dependencies will support loading any information from that file though, so it's likely you'll need to do a significant amount of work yourself on this.
