### ISSUE TITLE
Microsoft Visual C++ Build Tools - 404 error

### ISSUE THREAD

**Issue by theslimshaney** [requests/requests-kerberos#120]
While installing on Windows, I get this error:
```
building 'winkerberos' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
```

However, when visiting this website, a 404 error appears. Can the link be updated in the error message?

**Comment by theslimshaney** [comment]
Ah got it, thanks. This was from a pip install by the way.

**Comment by behackett** [comment]
The message is from setuptools, which pip uses to build C extensions:

https://github.com/pypa/setuptools/blob/6c2bccf360b7587cccbd59dd0b0b6081604f77c6/setuptools/msvc.py#L232-L236

**Comment by theslimshaney** [comment]
Thanks for the help!

**Comment by behackett** [comment]
My pleasure.

**Comment by theslimshaney** [comment]
Looks like there's already an issue open if anyone finds this in the future https://github.com/pypa/setuptools/issues/1394
