### ISSUE TITLE
Failed to install requests-kerberos using manual installation method

### ISSUE THREAD

**Issue by Zorrom** [requests/requests-kerberos#124]
Tried installing request-kerberos using the following python command but it failed with the following error message
$ tar -xvzf  requests-kerberos-0.12.0.tar.gz
$ cd requests-kerberos-0.12.0
$ python setup.py install

error in requests-kerberos setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

Kindly assist on this

**Comment by jfriar** [comment]
try updating your setuptools.  I'm using a virtualenv, so I did the following before trying to install requests-kerberos:

`./virtualenv/bin/pip install --upgrade setuptools`
