### ISSUE TITLE
Request is a replay (34)

### ISSUE THREAD

**Issue by funes79** [requests/requests-kerberos#135]
Hi, can't get through the authentication, using version 0.12.0, having a valid keytab in my cache, running a python script like this:

```
kerberos_auth = HTTPKerberosAuth(mutual_authentication=REQUIRED, sanitize_mutual_error_response=False)
r = requests.get('https://'+hiveserver_webui, auth=kerberos_auth, verify=filename)
```

Tried also
```
kerberos_auth = HTTPKerberosAuth(principal="myprincipal@REALM", mutual_authentication=REQUIRED, force_preemptive=True)
r = requests.get('https://'+hiveserver_webui, auth=kerberos_auth, verify=filename)
```

Also tried the options like DISABLED and OPTIONAL for `mutual_authentication`

```
<title>Error 403 GSSException: Failure unspecified at GSS-API level (Mechanism level: Request is a replay (34))</title>
</head>
<body><h2>HTTP ERROR 403</h2>
<p>Problem accessing /index.html. Reason:
<pre>    GSSException: Failure unspecified at GSS-API level (Mechanism level: Request is a replay (34))</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>
```

Tried also to kdestroy, kinit, run script again, but I got the same error.

**Comment by jborean93** [comment]
This is an error coming from your HTTP server saying that the Kerberos ticket that was used was seen as a replay. The biggest cause of this is the clocks between the various hosts are not in sync. By default 5 minutes is the largest clock skew that can be handled for Kerberos but this can be configured depending on your realm. If the clock skew is greater than this amount the service thinks the ticket is too old and so is a replay attempt which it won't allow.
