### ISSUE TITLE
Do not log Authorization headers

### ISSUE THREAD

**Issue by twosigmajab** [requests/requests-kerberos#137]
Authorization headers may contain sensitive information that should not be logged (even at DEBUG level). requests-kerberos is currently logging Authorization headers in the following places:

- https://github.com/requests/requests-kerberos/blob/d9c78fc3040481bf944306193ee5564ae6c4de31/requests_kerberos/kerberos_.py#L439
- https://github.com/requests/requests-kerberos/blob/d9c78fc3040481bf944306193ee5564ae6c4de31/requests_kerberos/kerberos_.py#L266-L267

Would you accept a patch that removes the contents of the header from these log messages?

Thanks for your consideration.

**Comment by jborean93** [comment]
Closing as per https://github.com/requests/requests-kerberos/pull/138#issuecomment-955600094
