### ISSUE TITLE
Can any one help  me out to solve this error

### ISSUE THREAD

**Issue by Darpana10** [requests/requests-kerberos#140]
Not bale to install Kerberos in my system. Used command "pip install kerberos"
Error:
C:\Users\mdarpana\AppData\Local\Programs\Python\Python38-32>pip install kerberos
Collecting kerberos
  Using cached https://files.pythonhosted.org/packages/34/18/9c86fdfdb27e0f7437b7d5a9e22975dcc382637b2a68baac07843be512fc/kerberos-1.3.0.tar.gz
Installing collected packages: kerberos
    Running setup.py install for kerberos ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\mdarpana\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mdarpana\\AppData\\Local\\Temp\\pip-install-34w6hul9\\kerberos\\setup.py'"'"'; __file__='"'"'C:\\Users\\mdarpana\\AppData\\Local\\Temp\\pip-install-34w6hul9\\kerberos\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\mdarpana\AppData\Local\Temp\pip-record-hq0n9_78\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\mdarpana\AppData\Local\Temp\pip-install-34w6hul9\kerberos\
    Complete output (5 lines):
    running install
    running build
    running build_ext
    building 'kerberos' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\mdarpana\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mdarpana\\AppData\\Local\\Temp\\pip-install-34w6hul9\\kerberos\\setup.py'"'"'; __file__='"'"'C:\\Users\\mdarpana\\AppData\\Local\\Temp\\pip-install-34w6hul9\\kerberos\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\mdarpana\AppData\Local\Temp\pip-record-hq0n9_78\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by behackett** [comment]
On Windows you want to install [WinKerberos](https://pypi.org/project/winkerberos/).

**Comment by jborean93** [comment]
Closing as per the above. On the `0.13.x` release the dependency has been changed to [pyspnego](https://pypi.org/project/pyspnego/).
