### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by wilberh** [requests/requests-kerberos#153]
I'm using this package as a plugin to another package (hdfs).  
To connect to a hadoop NameNode I've done - 

kinit (to obtain a Kerberos ticket), 
https protocol to connect to the host, 
passing an Explicit Principal (principal=user@realm:password), 

But I'm getting this error -
Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),)

Has anyone ran into this problem?

**Comment by jborean93** [comment]
This is nothing to do with requests-kerberos but the underlying requests session/request that you are generating. This library only handles the authentication aspect which is independent of whether HTTP or HTTPS is used.

**Comment by wilberh** [comment]
You're right; I just found the solution online.  
https://saagie.zendesk.com/hc/en-us/articles/360021384151-Read-Write-files-from-HDFS
