### ISSUE TITLE
Fatal error during installation of requests-kerberos

### ISSUE THREAD

**Issue by Ovesta** [requests/requests-kerberos#156]
I have fatal error during the installation of the package     requests-kerberos  :

In file included from src/kerberos.c:19:
src/kerberosbasic.h:17:10: fatal error: gssapi/gssapi.h: No such file or directory
   17 | #include <gssapi/gssapi.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by Ovesta** [comment]
Complite bash : 
ovesta@ovesta-Insp:~/Downloads/gitclones/requests-kerberos$ sudo python setup.py install
running install
running bdist_egg
running egg_info
creating requests_kerberos.egg-info
writing requests_kerberos.egg-info/PKG-INFO
writing dependency_links to requests_kerberos.egg-info/dependency_links.txt
writing requirements to requests_kerberos.egg-info/requires.txt
writing top-level names to requests_kerberos.egg-info/top_level.txt
writing manifest file 'requests_kerberos.egg-info/SOURCES.txt'
reading manifest file 'requests_kerberos.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'requests_kerberos.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/requests_kerberos
copying requests_kerberos/exceptions.py -> build/lib/requests_kerberos
copying requests_kerberos/compat.py -> build/lib/requests_kerberos
copying requests_kerberos/kerberos_.py -> build/lib/requests_kerberos
copying requests_kerberos/__init__.py -> build/lib/requests_kerberos
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/requests_kerberos
copying build/lib/requests_kerberos/exceptions.py -> build/bdist.linux-x86_64/egg/requests_kerberos
copying build/lib/requests_kerberos/compat.py -> build/bdist.linux-x86_64/egg/requests_kerberos
copying build/lib/requests_kerberos/kerberos_.py -> build/bdist.linux-x86_64/egg/requests_kerberos
copying build/lib/requests_kerberos/__init__.py -> build/bdist.linux-x86_64/egg/requests_kerberos
byte-compiling build/bdist.linux-x86_64/egg/requests_kerberos/exceptions.py to exceptions.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/requests_kerberos/compat.py to compat.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/requests_kerberos/kerberos_.py to kerberos_.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/requests_kerberos/__init__.py to __init__.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying requests_kerberos.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying requests_kerberos.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying requests_kerberos.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying requests_kerberos.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying requests_kerberos.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/requests_kerberos-0.13.0.dev0-py3.8.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing requests_kerberos-0.13.0.dev0-py3.8.egg
Copying requests_kerberos-0.13.0.dev0-py3.8.egg to /usr/local/lib/python3.8/dist-packages
Removing requests-kerberos 0.12.0 from easy-install.pth file
Adding requests-kerberos 0.13.0.dev0 to easy-install.pth file

Installed /usr/local/lib/python3.8/dist-packages/requests_kerberos-0.13.0.dev0-py3.8.egg
Processing dependencies for requests-kerberos==0.13.0.dev0
Searching for pykerberos<2.0.0,>=1.1.8
Reading https://pypi.org/simple/pykerberos/
Downloading https://files.pythonhosted.org/packages/af/e6/39e951de0d9d48a62335fde819e15f726846ea325e06ddbbb29a5273ef37/pykerberos-1.2.3.dev0.tar.gz#sha256=d667aa50f2dcefb6f2d563bd56c2b5eafc1183a6d8a07ec560d13d9c0d8ff29f
Best match: pykerberos 1.2.3.dev0
Processing pykerberos-1.2.3.dev0.tar.gz
Writing /tmp/easy_install-f76u6qpm/pykerberos-1.2.3.dev0/setup.cfg
Running pykerberos-1.2.3.dev0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-f76u6qpm/pykerberos-1.2.3.dev0/egg-dist-tmp-istdy1ub
In file included from src/kerberos.c:19:
src/kerberosbasic.h:17:10: fatal error: gssapi/gssapi.h: No such file or directory
   17 | #include <gssapi/gssapi.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by behackett** [comment]
I would guess that you don't have libkrb5, or the development headers for it, installed, which is required to build pykerberos.

**Comment by jborean93** [comment]
Closing as per the above, you need the `libkrb5` headers to be installed for the underlying library to be compiled.
