### ISSUE TITLE
gcc compile issue

### ISSUE THREAD

**Issue by lainsw** [requests/requests-kerberos#157]
When I run

pip install requests-kerberos 

I get the following error (full log file attached): [pip_install_requests-kerberos.log](https://github.com/requests/requests-kerberos/files/6633343/pip_install_requests-kerberos.log)

src/kerberosgss.c:876:12: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
        outloc = mempcpy(outloc, iov[1].buffer.value, iov[1].buffer.length);

Is there a flag or something missing in my config?

Other useful information:

About This Mac:
- OS X 10.15.7 (Catalina)

pip --version:
- (pip 20.2.4 from /opt/anaconda3/lib/python3.8/site-packages/pip (python 3.8))

gcc --version: 
- Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
- Apple clang version 12.0.0 (clang-1200.0.32.29)
- Target: x86_64-apple-darwin19.6.0
- Thread model: posix
- InstalledDir: /Library/Developer/CommandLineTools/usr/bin

src/kerberosgss.c:876:12: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
        outloc = mempcpy(outloc, iov[1].buffer.value, iov[1].buffer.length);

Is there a flag or something missing in my config?

**Comment by jborean93** [comment]
In the upcoming `0.13.x` release the Kerberos dependency has been changed to one that includes wheels for macOS removing the need to compile the libraries. They are also tested with more modern versions, unlike `pykerberos` so while you can still install it from source it's shouldn't be as hard anymore.
