### ISSUE TITLE
HTTPKerberosAuth not using correct TGT cache file 

### ISSUE THREAD

**Issue by dgotbaum** [requests/requests-kerberos#159]
Hello, 
I have kerberos installed on my windows machine and when I run a kinit and klist from the command prompt, it generates me a ticket for the principal I passed. When I run the kerberos request from jupyter notebook, it doesnt read the ticket I generated and instead logs me in as the current user. 
 
I have the env variable set up so that it points to the default key location
 
Is there anything I can do to specify a particular cache file? Sepecially when there are multiple in my machine?

**Comment by jborean93** [comment]
Closing as per the above.
