### ISSUE TITLE
is it a dead project

### ISSUE THREAD

**Issue by bioinfornatics** [requests/requests-kerberos#160]
Dear,

Firstly thanks for this library, we would like to know if this project is still alive indeed it seem that the latest commit is from 3 years ago.
Indeed before to start to use a such important piece of authentication we need to know if is project is still maintained.

Thanks

Best regards

**Comment by bioinfornatics** [comment]
Thanks @jborean93  
have a good day

**Comment by albertocavalcante** [comment]
> While I have commit access to this library it’s mostly just for critical bugfixes that may impact applications (that I need to support) that use this library. These thoughts are my own personal view of this library and other maintainers may have different thoughts.
> 
> IMO you should avoid this library for any new software in favour of libs like [pythongssapi/requests-gssapi](https://github.com/pythongssapi/requests-gssapi) (Linux) or [brandond/requests-negotiate-sspi](https://github.com/brandond/requests-negotiate-sspi) (Windows). These libraries use more modern libraries to call the C functions and are preferable to pykerberos (what this library uses).
> 
> You are free to continue using this library as it works for the basic Kerberos auth scenario but it doesn’t support all use cases.

@jborean93 just double checking, does the recommendation above remain true? Thanks

**Comment by jborean93** [comment]
Sure, this has been updated to use `pyspnego` so no longer has a dependency on `pykerberos` but I would highly recommend you still use those other libraries if you can. Unless there's some critical bug I'm probably not going to push any new changes here and consider this library "feature complete".
