### ISSUE TITLE
How to set the mechtype?

### ISSUE THREAD

**Issue by fomcl** [requests/requests-kerberos#184]
Hi,

How do I set the `mechtype` in `requests_kerberos`, like I set it in `httpx_gssapi` below? Is seems that this is not supported?
Without setting it to SPNEGO I get a 401 with equivalent `requests_kerberos` code.

```
import httpx
from gssapi import mechs
from httpx_gssapi import HTTPSPNEGOAuth

auth = HTTPSPNEGOAuth(mech=mechs.Mechanism.from_sasl_name("SPNEGO"), delegate=True)
with httpx.Client() as client:
    client.auth = auth
    resp = client.get(url) 
``` 

Thanks!

Albert-Jan

**Comment by jborean93** [comment]
You cannot, this is `requests-kerberos` and thus is for Kerberos only. If you want to be able to use other protocols you will have to use another library like [requests-gssapi](https://github.com/pythongssapi/requests-gssapi) which exposes a mech kwarg.
