### ISSUE TITLE
Can’t connect to server via non-canonical hostname

### ISSUE THREAD

**Issue by lukecyca** [requests/requests-kerberos#28]
I am trying to connect to a virtual host by way of a CNAME. The server’s reverse DNS does not resolve to the CNAME. I have created specific service princs for the CNAME and configured the server to use them.

When I connect to the server with curl, it works:

```
curl --negotiate --user : https://foo.example.com
```

If I check `klist` after doing so, I see `HTTP@foo.example.com/EXAMPLE.COM`.

When I connect with `requests` using this library, it does not work. The server keeps returning a 401. When I check `klist` after doing so, I don’t see the correct service princ. Instead, I see the service princ with the canonical hostname (as returned from reverse DNS).

It seems like [this issue](http://web.mit.edu/kerberos/krb5-current/doc/admin/princ_dns.html), but I’ve tried changing my client’s `krb5.conf` to include `rdns = false` and also `dns_canonicalize_hostname = false` (which I found by looking at the [krb5 source code](https://github.com/krb5/krb5/search?q=rdns&ref=cmdform)). Regardless, i’m mystified that `curl` (and also Safari) are able to successfully negotiate this connection no matter what `rdns` and `dns_canonicalize_hostname` are set to.

**Comment by alexsdutton** [comment]
Just to save a bit of time for people (like me) that find this and copy and paste…

The `libdefaults` param that makes everything better is called [`dns_canonicalize_hostname`](http://web.mit.edu/KERBEROS/krb5-1.12/doc/admin/conf_files/krb5_conf.html#libdefaults); I think @lukecyca typoed.

But thank you for writing this down; it's helped me sort out my kerberos woes! :-)
