### ISSUE TITLE
Reduce noise such as "handle_other(): Mutual authentication unavailable on 200 response" ?

### ISSUE THREAD

**Issue by romainr** [requests/requests-kerberos#45]
We are thinking about adding a 'if response.status_code != 200:'
on
https://github.com/requests/requests-kerberos/blob/master/requests_kerberos/kerberos_.py#L194
in order to avoid a bunch of noise.

(cf. https://issues.cloudera.org/browse/HUE-2198)

Does it make sense to you? Would you want a pull request?

**Comment by sigmavirus24** [comment]
Yes and no. Yes it makes sense to reduce the frequency of this for some users. No it shouldn't only check for a 200 status code. 

```py
if not response.ok:
```

Should cover this just fine. See: https://github.com/requests/requests-kerberos/pull/46

**Comment by romainr** [comment]
I see, thanks for the quick reply!
