### ISSUE TITLE
Open a session or get machine kerberos token

### ISSUE THREAD

**Issue by aimtsou** [requests/requests-kerberos#50]
I've used successfully the requests kerberos for authenticating my url. But for every url i construct i need to make another authentication, so my question is can i have a session for the program that is using the lib or can I somehow get machine kerberos token without having to authenticate every url?

**Comment by mkomitee** [comment]
That's a server-side decision. 

If the server prompts the client for authentication for every request, then yes, every request will need to be authenticated.

The application developer can chose to provide a secure/signed session cookie, and authenticate clients with that if it's available, and fall-back on kerberos if it is not, but we can't make that happen from within this library.

**Comment by rbcarson** [comment]
Closing old issue.
