### ISSUE TITLE
On Windows, 0.7.0 wheel still depends on kerberos module instead of kerberos_sspi

### ISSUE THREAD

**Issue by rbcarson** [requests/requests-kerberos#51]
#34 changed setup.py to require kerberos_sspi instead of kerberos==1.1.1. However, the [wheel for 0.7.0](https://pypi.python.org/packages/2.7/r/requests-kerberos/requests_kerberos-0.7.0-py2.py3-none-any.whl#md5=384f5ee3e9922bc790feda79f0441538) still has a metadata.json containing:

```
"run_requires": [{"requires": ["requests (>=1.1.0)", "kerberos (==1.1.1)"]}]
```

So on Windows, `pip install requests-kerberos` still tries to install kerberos instead of kerberos_sspi.

**Comment by AnthonyTruchet** [comment]
Hello, I just fixed this issue for my Windows + Python 3 (Anaconda) setup.
I'm pretty conscious the aforementioned pull request is not ready to be merged but I submit the fix in order to have you feedback and contribute.

**Comment by rbcarson** [comment]
@AnthonyTruchet Cool, looks like you got the tests to run on Windows! I never tried to run the tests, and did not try to use the module with Python 3, so I did not encounter the issues that you've fixed.

I may have a solution for the problem I've described in this issue, but I want to test it first.
