### ISSUE TITLE
incompatible with requests 1.1: mutual authentication fails because "Context is already fully established"

### ISSUE THREAD

**Issue by danc86** [requests/requests-kerberos#54]
This is not an issue with the latest requests versions, but with requests 1.1 and mutual authentication not disabled, a valid request will fail:

```
requests_kerberos.exceptions.MutualAuthenticationError: Unable to authenticate <Response [302]>
```

But it's not really a failure in mutual authentication, the problem is that the server is being authenticated twice and the second time raises a GSSAPI failure:

```
DEBUG:requests_kerberos.kerberos_:handle_401(): Handling: 401
DEBUG:requests_kerberos.kerberos_:authenticate_user(): Authorization header: Negotiate [...]
DEBUG:requests_kerberos.kerberos_:handle_other(): Handling: 302
DEBUG:requests_kerberos.kerberos_:handle_other(): Authenticating the server
DEBUG:requests_kerberos.kerberos_:authenticate_server(): Authenticate header: YIGZB[...]
DEBUG:requests_kerberos.kerberos_:authenticate_server(): returning <Response [302]>
DEBUG:requests_kerberos.kerberos_:handle_other(): returning <Response [302]>
DEBUG:requests_kerberos.kerberos_:handle_response(): returning <Response [302]>
DEBUG:requests_kerberos.kerberos_:authenticate_user(): returning <Response [302]>
DEBUG:requests_kerberos.kerberos_:handle_401(): returning <Response [302]>
DEBUG:requests_kerberos.kerberos_:handle_response(): returning <Response [302]>
DEBUG:requests_kerberos.kerberos_:handle_response() has seen 0 401 responses
DEBUG:requests_kerberos.kerberos_:handle_other(): Handling: 302
DEBUG:requests_kerberos.kerberos_:handle_other(): Authenticating the server
DEBUG:requests_kerberos.kerberos_:authenticate_server(): Authenticate header: YIGZB[...]
ERROR:requests_kerberos.kerberos_:authenticate_server(): authGSSClientStep() failed:
Traceback (most recent call last):
  File "requests_kerberos/kerberos_.py", line 230, in authenticate_server
    _negotiate_value(response))
GSSError: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Context is already fully established', 39756036))
ERROR:requests_kerberos.kerberos_:handle_other(): Mutual authentication failed
Traceback (most recent call last):
  File "asdf.py", line 8, in <module>
    auth=requests_kerberos.HTTPKerberosAuth(mutual_authentication=requests_kerberos.OPTIONAL))
  File "/usr/lib/python2.6/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 279, in request
    resp = self.send(prep, stream=stream, timeout=timeout, verify=verify, cert=cert, proxies=proxies)
  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 374, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests/adapters.py", line 219, in send
    r = self.build_response(request, resp)
  File "/usr/lib/python2.6/site-packages/requests/adapters.py", line 113, in build_response
    response = dispatch_hook('response', req.hooks, response)
  File "/usr/lib/python2.6/site-packages/requests/hooks.py", line 39, in dispatch_hook
    _hook_data = hook(hook_data)
  File "requests_kerberos/kerberos_.py", line 259, in handle_response
    return self.handle_response(_r, num_401s=num_401s, **kwargs)
  File "requests_kerberos/kerberos_.py", line 266, in handle_response
    _r = self.handle_other(response)
  File "requests_kerberos/kerberos_.py", line 190, in handle_other
    "{0}".format(response))
requests_kerberos.exceptions.MutualAuthenticationError: Unable to authenticate <Response [302]>
```

**Comment by danc86** [comment]
The difference seems to be that with latest requests, when ``authenticate_user`` re-sends the request the hook is not applied on the second request. I can't quite figure out why...

However with requests 1.1, the hook is invoked again on the second request, which is the first ``handle_other(): Handling: 302`` in the output above. Then ``handle_response`` calls ``handle_other`` *again* on the response it just got back, so it ends up called twice.

**Comment by danc86** [comment]
I believe this patch does the right thing with both requests 1.1 and newer versions:

```
--- a/requests_kerberos/kerberos_.py
+++ b/requests_kerberos/kerberos_.py
@@ -149,6 +149,7 @@ def authenticate_user(self, response, **kwargs):
         response.content
         response.raw.release_conn()
 
+        self.deregister(response)
         _r = response.connection.send(response.request, **kwargs)
         _r.history.append(response)
 
```

but it breaks a bunch of tests and I can't see any nice way to fix them, since the tests are poking around in the internals of HTTPKerberosAuth with mocks, instead of actually following the normal requests flow.

**Comment by jwdevel** [comment]
I have seen a similar issue but slightly different circumstances. The patch fixes it, so presumably the same problem.

I'm using requests 2.13.0 and requests_kerberos 0.11.0.

Here's my repro:

> $ python3
> Python 3.5.2 (default, Dec  6 2016, 23:41:55) 
> [GCC 4.4.6 20110731 (Red Hat 4.4.6-3)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import requests
> >>> requests.__version__
> '2.13.0'
> >>> from requests_kerberos import HTTPKerberosAuth
> >>>
> >>> import logging
> >>> logging.basicConfig()
> >>> logging.getLogger().setLevel(logging.DEBUG)
> >>> requests_log = logging.getLogger("requests.packages.urllib3")
> >>> requests_log.setLevel(logging.DEBUG)
> >>> requests_log.propagate = True
> >>> 
> >>> r = requests.get("https://mysite", auth=HTTPKerberosAuth(), verify=False)
> DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): mysite
> /home/jwdevel/.local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> DEBUG:requests.packages.urllib3.connectionpool:https://mysite:443 "GET / HTTP/1.1" 401 381
> DEBUG:requests_kerberos.kerberos_:handle_401(): Handling: 401
> DEBUG:requests_kerberos.kerberos_:authenticate_user(): Authorization header: Negotiate [long crypto key omitted]
> /home/jwdevel/.local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> DEBUG:requests.packages.urllib3.connectionpool:https://mysite:443 "GET / HTTP/1.1" 302 111
> DEBUG:requests_kerberos.kerberos_:authenticate_user(): returning <Response [302]>
> DEBUG:requests_kerberos.kerberos_:handle_401(): returning <Response [302]>
> DEBUG:requests_kerberos.kerberos_:handle_response(): returning <Response [302]>
> DEBUG:requests_kerberos.kerberos_:handle_response() has seen 0 401 responses
> DEBUG:requests_kerberos.kerberos_:handle_other(): Handling: 302
> DEBUG:requests_kerberos.kerberos_:handle_other(): Authenticating the server
> DEBUG:requests_kerberos.kerberos_:authenticate_server(): Authenticate header: [long crypto key omitted]
> DEBUG:requests_kerberos.kerberos_:authenticate_server(): returning <Response [302]>
> DEBUG:requests_kerberos.kerberos_:handle_other(): returning <Response [302]>
> DEBUG:requests_kerberos.kerberos_:handle_response(): returning <Response [302]>
> DEBUG:requests.packages.urllib3.connectionpool:Resetting dropped connection: mysite
> /home/jwdevel/.local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> DEBUG:requests.packages.urllib3.connectionpool:https://mysite:443 "GET /somefile HTTP/1.1" 200 9734
> DEBUG:requests_kerberos.kerberos_:handle_other(): Handling: 200
> DEBUG:requests_kerberos.kerberos_:handle_other(): Authenticating the server
> DEBUG:requests_kerberos.kerberos_:authenticate_server(): Authenticate header: [long crypto key omitted]
> ERROR:requests_kerberos.kerberos_:authenticate_server(): authGSSClientStep() failed:
> Traceback (most recent call last):
>   File "/home/jwdevel/.local/lib/python3.5/site-packages/requests_kerberos/kerberos_.py", line 261, in authenticate_server
>     _negotiate_value(response))
> kerberos.GSSError: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Context is already fully established', 39756036))
> ERROR:requests_kerberos.kerberos_:handle_other(): Mutual authentication failed
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/jwdevel/.local/lib/python3.5/site-packages/requests/api.py", line 70, in get
>     return request('get', url, params=params, **kwargs)
>   File "/home/jwdevel/.local/lib/python3.5/site-packages/requests/api.py", line 56, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/home/jwdevel/.local/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/home/jwdevel/.local/lib/python3.5/site-packages/requests/sessions.py", line 630, in send
>     history = [resp for resp in gen] if allow_redirects else []
>   File "/home/jwdevel/.local/lib/python3.5/site-packages/requests/sessions.py", line 630, in <listcomp>
>     history = [resp for resp in gen] if allow_redirects else []
>   File "/home/jwdevel/.local/lib/python3.5/site-packages/requests/sessions.py", line 190, in resolve_redirects
>     **adapter_kwargs
>   File "/home/jwdevel/.local/lib/python3.5/site-packages/requests/sessions.py", line 615, in send
>     r = dispatch_hook('response', hooks, r, **kwargs)
>   File "/home/jwdevel/.local/lib/python3.5/site-packages/requests/hooks.py", line 31, in dispatch_hook
>     _hook_data = hook(hook_data, **kwargs)
>   File "/home/jwdevel/.local/lib/python3.5/site-packages/requests_kerberos/kerberos_.py", line 297, in handle_response
>     _r = self.handle_other(response)
>   File "/home/jwdevel/.local/lib/python3.5/site-packages/requests_kerberos/kerberos_.py", line 220, in handle_other
>     "{0}".format(response))
> requests_kerberos.exceptions.MutualAuthenticationError: Unable to authenticate <Response [200]>
> >>>

**Comment by cbchhaya** [comment]
This is still a problem with requests 2.18.4 and request_kerberos 0.12.0.

I see the issue has been open for 3 years now -- are there any plans to put a fix in?

`-bash-4.2$ python
Python 2.7.5 (default, May  3 2017, 07:55:04)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-14)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> import requests_kerberos as k
>>> r = requests.get("https://<host>/krb", auth=k.HTTPKerberosAuth())`

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[HOME_DIR]/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "[HOME_DIR]/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "[HOME_DIR]/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "[HOME_DIR]/lib/python2.7/site-packages/requests/sessions.py", line 625, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "[HOME_DIR]/lib/python2.7/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "[HOME_DIR]/lib/python2.7/site-packages/requests_kerberos/kerberos_.py", line 404, in handle_response
    return self.handle_response(_r, num_401s=num_401s, **kwargs)
  File "[HOME_DIR]/lib/python2.7/site-packages/requests_kerberos/kerberos_.py", line 411, in handle_response
    _r = self.handle_other(response)
  File "[HOME_DIR]/lib/python2.7/site-packages/requests_kerberos/kerberos_.py", line 336, in handle_other
    "{0}".format(response))
requests_kerberos.exceptions.MutualAuthenticationError: Unable to authenticate <Response [200]>`

**Comment by alv000h** [comment]
+1

**Comment by rsaim** [comment]
+1

**Comment by jborean93** [comment]
See https://github.com/requests/requests-kerberos/issues/94#issuecomment-955603801
