### ISSUE TITLE
Use of Kerberos 1.2.2 on Setup.Py (or requirements.txt rather)

### ISSUE THREAD

**Issue by gcavalcante8808** [requests/requests-kerberos#58]
Hello Folks,

I tested requests-kerberos with PyKerberos version 1.2.2 (recently provided by Apple) and it works with a minor change on the PyKerberos Side for use with python 3.

For me, PyKerberos 1.1.1 wont work as well (python 3.4, no 'commands' on import), but with 1.2.2 version it worked well.

Any change to remove the version requirement from the setup.py?

**Comment by laserson** [comment]
+1

**Comment by akaIDIOT** [comment]
:+1: 

Just modified the line in `setup.py` to `requires.append('kerberos>=1.1.1')` to be able to install this, seems to work as intended. Can confirm this fixes things for 3.4.

**Comment by mkomitee** [comment]
:+1:

**Comment by rbcarson** [comment]
#56 switches from kerberos to pykerberos, which should solve the Python 3 problems. See also: #37. Hopefully this solution works for you.
