### ISSUE TITLE
Please create a new release on pypi

### ISSUE THREAD

**Issue by smetj** [requests/requests-kerberos#61]
On pypi requests-kerberos is still pulling in the "kerberos" package dependency which causes memory leaks.

The latest commit appears to depend on pykerberos which doesn't seem to suffer from that.

**Comment by Lukasa** [comment]
Thanks for this reminder. =) I'll aim to release this in the next few days.

**Comment by sigmavirus24** [comment]
@Lukasa ?

**Comment by Lukasa** [comment]
Ah thanks for reminding me: will release tomorrow.

**Comment by Lukasa** [comment]
I've just pushed v0.8.0.

**Comment by smetj** [comment]
Thank you!
