### ISSUE TITLE
error installing 1.2.2 (py2.7) from pypi tar.gz file

### ISSUE THREAD

**Issue by raderaj** [requests/requests-kerberos#62]
I'm having issues installing this on a Linux RedHat machine (Red Hat Enterprise Linux Server release 6.6 (Santiago)). Any help/suggestions would be appreciated. 

My version of gcc is the following:
gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I have Python 2.7.10 (Anaconda 2.3.0 64-bit) installed.

Here is the error message I get from running pip install:

Downloading/unpacking http://XXXX/repo/request-kerberos/kerberos-1.2.2.tar.gz
  Downloading kerberos-1.2.2.tar.gz
  Downloading from URL http://XXXX/repo/request-kerberos/kerberos-1.2.2.tar.gz
  Running setup.py (path:/tmp/pip-EmXm8a-build/setup.py) egg_info for package from http://XXXX/repo/request-kerberos/kerberos-1.2.2.tar.gz
    running egg_info
    creating pip-egg-info/kerberos.egg-info
    writing pip-egg-info/kerberos.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/kerberos.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/kerberos.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/kerberos.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/kerberos.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/kerberos.egg-info/SOURCES.txt'
  Source in /tmp/pip-EmXm8a-build has version 1.2.2, which satisfies requirement kerberos==1.2.2 from http://XXXX/repo/request-kerberos/kerberos-1.2.2.tar.gz
Installing collected packages: kerberos
  Running setup.py install for kerberos
    Running command /opt/anaconda/2.1.0/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-EmXm8a-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-veTkaH-record/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_ext
    building 'kerberos' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/anaconda/2.1.0/include/python2.7 -c src/base64.c -o build/temp.linux-x86_64-2.7/src/base64.o sh: krb5-config: command not found
    gcc: sh:: No such file or directory
    gcc: krb5-config:: No such file or directory
    gcc: command: No such file or directory
    gcc: not: No such file or directory
    gcc: found: No such file or directory
    error: command 'gcc' failed with exit status 1
    Complete output from command /opt/anaconda/2.1.0/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-EmXm8a-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-veTkaH-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_ext

building 'kerberos' extension

creating build

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/src

gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/anaconda/2.1.0/include/python2.7 -c src/base64.c -o build/temp.linux-x86_64-2.7/src/base64.o sh: krb5-config: command not found

gcc: sh:: No such file or directory

gcc: krb5-config:: No such file or directory

gcc: command: No such file or directory

gcc: not: No such file or directory

gcc: found: No such file or directory

error: command 'gcc' failed with exit status 1

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_hdoopadm...
Command /opt/anaconda/2.1.0/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-EmXm8a-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-veTkaH-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-EmXm8a-build
Exception information:
Traceback (most recent call last):
  File "/opt/anaconda/2.1.0/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/opt/anaconda/2.1.0/lib/python2.7/site-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/opt/anaconda/2.1.0/lib/python2.7/site-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/opt/anaconda/2.1.0/lib/python2.7/site-packages/pip/req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/opt/anaconda/2.1.0/lib/python2.7/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /opt/anaconda/2.1.0/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-EmXm8a-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-veTkaH-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-EmXm8a-build

**Comment by Lukasa** [comment]
Hmm, looks like there's an expectation you'll have the file krb5-config and you don't. Can you try running `yum provides krb5-config` to see what package you need, and then install it?

**Comment by sigmavirus24** [comment]
@raderaj any updates on this?

**Comment by pprett** [comment]
when i run `yum provides` it gives me ```
krb5-devel-1.6.1-80.el5_11.i386 : Development files needed to compile Kerberos 5
                                : programs.
Repo        : installed
Matched from:
Filename    : /usr/kerberos/bin/krb5-config
```

maybe putting /usr/kerberos/bin into the PATH will fix it?

**Comment by raderaj** [comment]
Thanks -- I didn't have root on the system and after getting the system admins to run yum it looks like it works now. Closing issue.
