### ISSUE TITLE
Add preemptive authentication

### ISSUE THREAD

**Issue by laurivosandi** [requests/requests-kerberos#65]
I'd like to use opportunistic authentication on the server end and simply check for WWW-Authenticate header presence. The main idea is to prevent the first HTTP request which will always return 401 and instead supply the Kerberos credentials immideately. At first glance it seems to be pretty easy to implement on the client side.

**Comment by Lukasa** [comment]
I'm open to seeing this as an option.

**Comment by laurivosandi** [comment]
Thanks, works like a charm! :)
