### ISSUE TITLE
Add optional support for WinKerberos

### ISSUE THREAD

**Issue by behackett** [requests/requests-kerberos#67]
[WinKerberos](https://pypi.python.org/pypi/winkerberos) is a kerberos/pykerberos/kerberos-sspi work-alike for Windows SSPI with no dependencies (no need to install pywin32). It is actively maintained, responsive to bug reports, enhancement requests, and pull requests (though I haven't seen any PRs yet). It supports some features kerberos-sspi does not (the ability to authenticate as a different kerberos user than the process owner) and some features [kerberos-sspi can not](https://github.com/may-day/kerberos-sspi/issues/1). it should be a drop in alternative.

**Comment by rbcarson** [comment]
This looks sweet! I'll look into it as soon as I can.
