### ISSUE TITLE
Mutual auth REQUIRED fails w/ persistent connection

### ISSUE THREAD

**Issue by nitzmahone** [requests/requests-kerberos#68]
When communicating with a Windows wsman endpoint using requests-kerberos, we should be able to set mutual auth to REQUIRED. However, the server stops sending auth responses on persistent connections after a successful exchange, which causes requests-kerberos to fail for mutual auth on subsequent responses (because the WWW-Authenticate response header is missing). If authentication is  repeated on every request, the server will emit the proper headers in the response, but that behavior isn't currently implemented by requests-kerberos. 

I'm not familiar enough with the various RFCs to be sure, but I think this behavior falls into a gray area that's not well documented. 

I'm guessing one of two things should happen here:
1) Mutual auth REQUIRED forces reauthentication on each request (sub-optimal for performance, probably more so in delegated cases). A fix for this could also probably easily address #65.

2) Add stateful auth code to requests-kerberos that recognizes a successful auth exchange and won't try to validate mutual auth for implied-prior-auth responses on persistent connections. It'd still need to watch for 401s and reauthenticate accordingly (eg, proxies w/o Proxy-Support: Session-Based-Authentication), and it might need to be connection-aware to avoid a connection-hijacking attack via a compromised proxy (assuming requests surfaces what we'd need to know).

I can take a stab at implementing one of these behaviors, but I'm not sure which one is more correct. I'd lean toward 2) for performance, but implementing connection-aware behavior could be problematic. 1) should be more straightforward, but may have a performance penalty.

**Comment by Lukasa** [comment]
HTTP authentication is never connection-based, it's always transactional. That is, a single request is authed. This was a major part of why NTLM was a problem for HTTP: NTLM authenticated connections, rather than transactions.

With the additional fact that urllib3 will transparently reconnect when a HTTP connection has been lost (e.g. because it fell idle), I don't think you could implement 2 with any grace, even if it was a good idea.

That said, I'd be interested to see what, say, Firefox or curl do for mutual auth. @bagder, mind lending us your wisdom?

**Comment by nitzmahone** [comment]
That's kinda what I was afraid of- Microsoft's HTTP kerberos auth impl is clearly "optimizing" for the same connection-based semantics as NTLM (though will at least present the proper WWW-Authenticate responses so long as an Authorization header is always present in the requests). Sounds like option 1 might be the way to go, then (should be easier anyway).

**Comment by bagder** [comment]
Are you talking mutual auth as in [draft-ietf-httpauth-mutual](https://tools.ietf.org/html/draft-ietf-httpauth-mutual-06) ? I've seen no interest for this in the browser corner of the world as HTTP authentication is basically not being used much anymore in favor of form+cookies etc.

We don't support it in curl, but we've been through hell and back to support NTLM and it never stops biting us. Connection-based auth in HTTP is a pain. Still, anything protocol-like you throw at curl sticks so we will probably support that too one day...

**Comment by nitzmahone** [comment]
@bagder This is specific to kerberos- basically, do we attempt to decrypt the final WWW-Authenticate response header with our session key to ensure that it came from the server we think we're communicating with, vs just ignoring it and saying, "welp, we got a 200 and a response, good to go!"- REQUIRED says we always validate and error if missing, OPTIONAL says validate if present (but ignore if missing), and DISABLED always ignores. I'm not sure how much value that final check really adds, though- I haven't thought through all the different attack mechanisms.
