### ISSUE TITLE
TypeError: authGSSClientInit() got an unexpected keyword argument 'principal'

### ISSUE THREAD

**Issue by syvanen** [requests/requests-kerberos#71]
Looks like now that kerberos-sspi (https://github.com/may-day/kerberos-sspi/blob/master/kerberos_sspi.py#L170) doesn't support 'principal' that was added in commit https://github.com/requests/requests-kerberos/commit/c464cc0035a5552ab28b9e8c3eee7a5904f33996.

**Comment by louahola** [comment]
+1

**Comment by rbcarson** [comment]
It seems like [sspi in pywin32 supports it and calls it `client_name`](https://github.com/SublimeText/Pywin32/blob/master/lib/x32/win32/lib/sspi.py#L95), but [kerberos-sspi doesn't support passing it through](https://github.com/may-day/kerberos-sspi/blob/master/kerberos_sspi.py#L170).

@behackett It looks like [WinKerberos supports this](https://github.com/mongodb-labs/winkerberos/blob/master/src/winkerberos.c#L224). Agree?

**Comment by behackett** [comment]
Yes, WinKerberos supports this argument.

**Comment by BenjaminWLarson** [comment]
+1

I've gotten pywinrm to work with basic authentication, but I need kerberos to work with it and I'm getting the exact same error.

Using Python 3.4.3

**Comment by behackett** [comment]
If you find that users need support for the principal option, WinKerberos does support it. It's a drop in replacement for pykerberos / kerberos-sspi.

**Comment by rbcarson** [comment]
@behackett I intend to try out WinKerberos once I find the time. I'd like to have it replace kerberos-sspi + pywin32 at the minimum, because those dependencies are fairly unpleasant (as I'm sure you know), despite being the easiest solution on Windows prior to WinKerberos.
