### ISSUE TITLE
v0.10.0 missing from PyPI

### ISSUE THREAD

**Issue by danc86** [requests/requests-kerberos#77]
The latest version [published on PyPI](https://pypi.python.org/pypi/requests-kerberos) is currently 0.9.0, but I can see here on GitHub that 0.10.0 has been released for a while now.

Can you please upload 0.10.0 to PyPI?

**Comment by rbcarson** [comment]
It's already on PyPI, but there seems to be some glitch that's making it not appear as the latest available version.

See https://pypi.python.org/pypi/requests-kerberos/0.10.0.

**Comment by Lukasa** [comment]
Yup, it was already pushed, but PyPI didn't hide the 0.9 release for some reason. I've manually hidden it now.
