### ISSUE TITLE
Need requests-kerberos for f23 OS

### ISSUE THREAD

**Issue by bliuredhat** [requests/requests-kerberos#80]
Hi, guys;
Can you help to distributed the new package of python-requests-kerberos for f23 ? And in current situation(http://koji.fedoraproject.org/koji/packageinfo?packageID=16282), can't find the package for f23.
thank you~!

**Comment by Lukasa** [comment]
Sorry, but the requests-kerberos team is concerned only with distribution via pip. For any other distribution method you'll need to get in contact with your downstream packaging team.
