### ISSUE TITLE
compiled with Address Sanitizer?

### ISSUE THREAD

**Issue by hmijail** [requests/requests-kerberos#81]
I don't know whether this should be reported here - please let me know where to go if not.

When installing requests-kerberos (with pip in a Python 3.5.2 installation in macOS 10.12 Sierra), a file "kerberos.cpython-35m-darwin.so" gets installed (in my case in a venv: venv/lib/python3.5/site-packages/kerberos.cpython-35m-darwin.so). 

This .so file seems to have been compiled using clang's Address Sanitizer, and triggers this error message:
```
==78358==ERROR: Interceptors are not working. This may be because AddressSanitizer is loaded too late (e.g. via dlopen). Please launch the executable with:
DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib
==78358==AddressSanitizer CHECK failed: /Library/Caches/com.apple.xbs/Sources/clang_compiler_rt/clang-800.0.38/src/projects/compiler-rt/lib/sanitizer_common/sanitizer_mac.cc:690 "(("interceptors not installed" && 0)) != (0)" (0x0, 0x0)
    <empty stack>

Abort trap: 6
```

Now, I'm not 100% sure that it's requests-kerberos the guilty party here, but it is the only suspect. There are no more native files in my venv, and `otool -lL kerberos.cpython-35m-darwin.so` does show a smoking gun: it refers to dylib `	@rpath/libclang_rt.asan_osx_dynamic.dylib (compatibility version 0.0.0, current version 0.0.0)`, and has a load command like this:
```
Load command 17
          cmd LC_RPATH
      cmdsize 136
         path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/lib/darwin (offset 12)
```
Can you please confirm whether I got it right?

And if so, when do you plan to get out a new version not compiled with the sanitizer? :)

(note, I have tried setting the DYLD_INSERT_LIBRARIES and it doesn't work)

**Comment by rbcarson** [comment]
requests-kerberos itself is pure Python, but its dependencies are not. You probably want to pursue this issue with the folks that maintain the Python Kerberos and/or PyKerberos libraries.

**Comment by hmijail** [comment]
Oh OK, seems to be actually installed by pykerberos. Sorry, I'm not a Python specialist :).

**Comment by rbcarson** [comment]
It's all good. :)
