### ISSUE TITLE
'KDC has no support for encryption type in 'generate_request_header'

### ISSUE THREAD

**Issue by sansagara** [requests/requests-kerberos#82]
Hello. I'm using [this](https://github.com/mtth/hdfs) library to connect to a kerberized HttpFS service on Hadoop.  It uses requests-kerberos for that purpose.

When connecting with accounts on the default realm, ( a Linux MIT Kerberos Server), the request goes smoothly. But when attempting the same but with accounts from an Active Directory server on another domain, i keep getting this error:

`File "/usr/local/lib/python3.5/site-packages/requests_kerberos/kerberos_.py", line 144, in generate_request_header
    negotiate_resp_value)
kerberos.GSSError: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ( 'KDC has no support for encryption type' , -1765328370))
`

My first guess was that requests_kerberos doesn't support AES-256 by default, and  my HttpFS (WebHDFS) service is wanting to use the strongest encryption that is enabled both on the Kerberos Realm and the AD domain, which is AES256. I'm not so sure anymore. 

Is anything apparent i'm missing?
TY

**Comment by rbcarson** [comment]
Your guess is as good as mine here. requests-kerberos is just a wrapper around this [PyKerberos](https://pypi.python.org/pypi/pykerberos), which itself is a fork of [Apple's Kerberos](https://pypi.python.org/pypi/kerberos), the de facto standard.

On Windows, requests-kerberos has a different dependency. It ends up being a wrapper around the native Kerberos implementation through pywin32. It would be interesting to explore whether this Windows dependency would work with your Active Directory server.

**Comment by behackett** [comment]
A quick Google search for the error message turns up a bunch of results. For example:

https://support.symantec.com/en_US/article.TECH220711.html

The message would seem to indicate that Active Directory isn't configured to support the requested cipher. I don't know how you would even configure this in PyKerberos or any of the other python kerberos libraries.

**Comment by sansagara** [comment]
I checked the tickets i get when kiniting from the default, local realm with the one i get when kiniting from active directory. The only real difference is the realm, as using `klist -e` displays `Etype (skey, tkt): aes256-cts-hmac-sha1-96, aes256-cts-hmac-sha1-96` on both of them.

**Comment by behackett** [comment]
I don't see a way that a client library can influence this in MIT Kerberos or Windows SSPI. From the traceback you posted you seem to be using pykerberos on Unix, rather than kerberos-sspi on Windows.  Maybe there is some kind of incompatibility between Active Directory and the version of MIT krb5 / Hiemdal on your machine?

**Comment by sansagara** [comment]
@behackett It may be the case, yes. But again, there's the thing that requests using the native hdfs command-line interface work as expected when using tickets created with these AD accounts.  It may be the case that Java provides a different mechanism for generating the requests that does not give any exception. But unfortunately, it will be a hard to test issue. If any other ideas come by, they are appreciated.
For now, i'm sticking with local, default realm Kerberos accounts for this particular task.
TY
