### ISSUE TITLE
http proxy negotiate/gssapi authentication?

### ISSUE THREAD

**Issue by benley** [requests/requests-kerberos#83]
I was hoping to find a `HTTPProxyKerberosAuth` class to enable working with http proxies that require NEGOTIATE gssapi auth, like [certain configurations of squid](http://wiki.squid-cache.org/Features/NegotiateAuthentication).  Is there a way to use requests-kerberos handle that scenario as it currently stands?

This would be akin to [HTTPProxyDigestAuth from requests-toolbelt](https://github.com/sigmavirus24/requests-toolbelt/blob/e5f66d44edf0ef1072f1c0c77b00eff0a8c76c31/requests_toolbelt/auth/http_proxy_digest.py#L10), if the necessary code doesn't already exist somewhere.

**Comment by Lukasa** [comment]
requests-kerberos cannot currently handle that kind of authentication.

**Comment by benley** [comment]
Is it something that belongs in this project, or am I barking up the wrong tree?

**Comment by Lukasa** [comment]
It definitely belongs in this project. =) Unfortunately, I have very little time to tackle writing such a thing, so I'll have to leave this open to someone else who can find that time.

**Comment by rbcarson** [comment]
This would be nice to have! However, Requests doesn't support multiple auth handlers, so it can be a problem if you want to use one auth method for the proxy, and another for the actual request. This is already an issue with HttpNtlmAuth from requests-ntlm, though I don't know if the problem's tracked anywhere.

HttpNtlmAuth also handles NTLM authentication for either a proxy or a website, based on what response header it sees first, which makes it a bit of an oddball.

**Comment by NurcanSonmez** [comment]
Hi everyone! Any ideas how the proxy auth can be done with requests-kerberos?
 It's been a while since this ticket is opened, just wanted to check.

**Comment by NurcanSonmez** [comment]
When I use IP address as the auth surrogate in the proxy the following works, however, when I use no surrogate it doesn't work. Just sharing the code in case it'll help others.
`
import requests
from requests_kerberos import HTTPKerberosAuth, REQUIRED`
`PROXY = {'https': 'http://yourproxy:80'}`
`s = requests.Session()`
`response = s.get("http://yourproxy:80",auth=HTTPKerberosAuth(force_preemptive=True))`
`response_cnn = s.get("https://www.cnn.com", proxies=PROXY, verify=False, headers={"Proxy-Authorization": response.request.headers['Authorization']})`

**Comment by ManWalkingBy** [comment]
@NurcanSonmez , Thanks for your code, it was very useful for me when I just ran into this problem. But with requests https, it really doesn't work. Having studied the code of Requests, I realized that the authentication data (that was placed in the request header) does not reach the method "set_tunnel" (module httplib(py2)/http.client(py3)). I used the following code to solve this problem:
````
import requests
from requests_kerberos import HTTPKerberosAuth
from urllib3.util import parse_url

class HTTPAdapterWithProxyKerberosAuth(requests.adapters.HTTPAdapter):
    def proxy_headers(self, proxy):
        headers = {}
        auth = HTTPKerberosAuth()
        negotiate_details = auth.generate_request_header(None, parse_url(proxy).host, is_preemptive=True)
        headers['Proxy-Authorization'] = negotiate_details
        return headers

session = requests.Session()
session.proxies = {'http': 'http://yourproxy:proxyport', 'https': 'http://yourproxy:proxyport'}
session.mount('https://', HTTPAdapterWithProxyKerberosAuth())

response = session.get(r"https://www.google.com/")
````
Maybe it will be useful for someone.

**Comment by jborean93** [comment]
Support for proxying `http` endpoints has been added with https://github.com/requests/requests-kerberos/issues/148. As mentioned above using this for `https` endpoints is not supported due to limitations with the underlying libraries that are used. Until this is fixed we can only offer support for `http` endpoints.
