### ISSUE TITLE
Does requests-kerberos fully support GSS_S_CONTINUE NEEDED?

### ISSUE THREAD

**Issue by spaetow** [requests/requests-kerberos#84]
This is more a question about whether the object supports the GSS_S_CONTINUE_NEEDED status (and handles it correctly). I ask this because I have to be able to use Python objects that support this status (and handle it). The only alternative otherwise is using the 'gssapi' object and construct things myself.

**Comment by rbcarson** [comment]
Sorry, I'm not familiar with the intricacies of the implementation, so I can't test this scenario myself. You're probably in the best position to test this and report back.

**Comment by jborean93** [comment]
The library doesn't really support it as Kerberos is expected to just have 1 exchange of tokens and thus doesn't expect the continue message.
