### ISSUE TITLE
Support for kerberos keytab ?

### ISSUE THREAD

**Issue by ultrabug** [requests/requests-kerberos#86]
Hi guys,

I'd like to know if or how it would be possible for requests-kerberos to support a **keytab** option ?

We can specify a principal alright but no keytab that I know of ?

Related discussion : https://github.com/mtth/hdfs/issues/63

ping @ericjang96

**Comment by Lukasa** [comment]
In principle, sure, but I don't think that there is any way to specify where to look for a keytab in either pykerberos or winkerberos. I think pykerberos can *use* a keytab assuming it finds one, but winkerberos doesn't appear to have any code for it.

Either way, if you can work out how to get those two libraries to use a keytab, we'll merge a patch to expose the functionality.

**Comment by behackett** [comment]
I don't see a way in GSSAPI to specify an explicit keytab in code, but maybe there is a way in libkrb5's API. If you're using krb5 1.11+ you can set the KRB5_CLIENT_KTNAME env variable.

SSPI doesn't appear to deal with keytab files at all, though Microsoft provides the ktpass tool to generate keytab files related to Active Directory KDCs for use on non-Windows systems.

If someone knows of a way to make pykerberos use an explicit keytab file I'd be happy to see if I can do something similar in winkerberos.

**Comment by ultrabug** [comment]
Thanks for your input and replies guys

I'll try to look into pykerberos when I can then.

**Comment by ultrabug** [comment]
Thanks @behackett, from my tests all we have to do is set the `KRB5_CLIENT_KTNAME` env to point to a keytab file and all subsequent usage of the lib get automagically authenticated 😲 

Don't even need to set the principal... nice !

ping @ericjang96 @mtth FYI

**Comment by vasuks** [comment]
@ultrabug - I also have a requirement to do kerberos authentication with principal and keytab file. Could you please provide the code snippet and python packages used for this

**Comment by ultrabug** [comment]
@Sophie-Stratton I got it working on Linux only. I have no clue about env passing in Windows I'm afraid, sorry :(

**Comment by mzola** [comment]
@ultrabug I'm using os.environ["KRB5_CLIENT_KTNAME"] to point to a keytab file but I get this error: 'Principal in credential cache does not match desired name'. If I issue a kinit with the same key before running the scripts it works, do you have any idea why?

**Comment by DirtyJerz** [comment]
@mzola I was running into the same problem. While debugging a script to use a service account and keytab, I tried the above solutions using os.environ["KRB5_CLIENT_KTNAME"] = "<keytab>". Turns out I couldn't get Kerberos/GSSAPI to try to issue a ticket because I already had a ticket under my domain user acct principal. 

The workaround i found was to use k5start:
```
$ /usr/bin/k5start -b -U -f /home/username/principal.keytab -k /run/k5start/krbcc -o principal -K 10 -l 10h -p /run/k5start/k5start.pid
```
(I used the above in a in a systemd unitfile to persists across reboots. )
Then use the credential cache created by the unitfile in the python code like this:
```
os.environ["KRB5CCNAME"] = "<krbcc_name>"
```
That way GSSAPI will use that credential cache when checking the principal specified in HTTPKerberosAuth param.

**Comment by elbakramer** [comment]
```python
from spnego import KerberosKeytab
principal = "..."
keytab = "..."


cred = KerberosKeytab(keytab, principal)
```

**Comment by bnh1** [comment]
> Try this code snippet:
> 
> ```python
> from spnego import KerberosKeytab
> from request_kerberos import HTTPKerberosAuth
> 
> principal = "..."
> keytab = "..."
> 
> cred = KerberosKeytab(keytab, principal)
> auth = HTTPKerberosAuth(principal=cred)
> 
> response = requests.get(url, auth=auth)
> ```

@elbakramer 
Thank you so much for this example, it is/was very helpful.  

With that bit of code and including `mutual_authentication=OPTIONAL`, I'm able to authenticate with a keytab to a Microsoft SCCM "AdminService" API using MS's "Negotiate" authentication type.

```
import requests
requests.packages.urllib3.disable_warnings()
from requests_kerberos import HTTPKerberosAuth, OPTIONAL
from spnego import KerberosKeytab

keytab = KerberosKeytab('./<myprincipal>.keytab',
                        principal='<myprincipal>@<myrealm>')
kerberos_auth = HTTPKerberosAuth(principal=keytab,
                                 mutual_authentication=OPTIONAL)

r = requests.get("https://<SCCMServer>/AdminService/wmi/SMS_Site",
                            auth=kerberos_auth, verify=False)
print(r.json()['value'])
```

And in case it may help someone else, the `ktpass` command to create the keytab for the AD principal on a Windows box was:
```
ktpass -out <myprincipal>.keytab -pass * -princ <myprincipal>@<myreal> -crypto ALL -ptype KRB5_NT_PRINCIPAL
```
