### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by ajak6** [requests/requests-kerberos#88]
I am running a script which internally uses this library. I cannot find a way to install this dependency. 
I am using Mac and trieid pip install kerberos_sspi but it again throws error
lib/python2.7/site-packages/requests_kerberos/kerberos_.py", line 4, in <module>
    import kerberos_sspi as kerberos
ImportError: No module named kerberos_sspi

**Comment by ajak6** [comment]
```
Collecting kerberos_sspi

  Downloading kerberos-sspi-0.2.tar.gz
Collecting pywin32 (from kerberos_sspi)
  Could not find a version that satisfies the requirement pywin32 (from kerberos_sspi) (from versions: )
No matching distribution found for pywin32 (from kerberos_sspi)

```

**Comment by Lukasa** [comment]
Can you try upgrading pip and try again?

**Comment by ajak6** [comment]
Its already upgraded to latest.
Requirement already up-to-date: pip in /usr/local/lib/python2.7/site-packages

**Comment by Lukasa** [comment]
Ok, so why are you installing kerberos_sspi? It shouldn't be required. What version of requests-kerberos are you trying to install?

**Comment by sigmavirus24** [comment]
That import isn't even in the current version of requests-kerberos.

**Comment by ajak6** [comment]
It looks to be an internally cached version of this library and is not latest. Looks to be 0.8.x ver. Any hints how can I debug this? Is it because of the platform?  I tried on unix as well though, I don't get error for requests_kerberos but get an error for kerberos_sspi

**Comment by Lukasa** [comment]
I'm afraid we don't really provide support for older versions of the software: we recommend you upgrade.

**Comment by ajak6** [comment]
However I am not sure why it looking for sspi, which looks to be related to windows platform.

**Comment by Lukasa** [comment]
Indeed, it seems like that would have been a mistake. However, we know that the new version does not do that, so I continue to recommend that you upgrade.

**Comment by ajak6** [comment]
as it is a internally cached version. I cannot upgrade it as some other team maintains the third party libraries. if this would have been an issue other people would have seen it.

**Comment by Lukasa** [comment]
That's fair enough, but as I said: we're not really in a position to provide support for anything but the current release of the software.

**Comment by ajak6** [comment]
Sure Thanks.

**Comment by elisicad** [comment]
Does anyone know how to install requests_kerberos on linux? I have this line in my code:
from requests_kerberos import HTTPKerberosAuth, OPTIONAL
 and I get this errror:
ImportError: No module named 'requests_kerberos'
