### ISSUE TITLE
TypeError: __call__() missing 1 required positional argument: 'request'

### ISSUE THREAD

**Issue by toasteez** [requests/requests-kerberos#91]
I am recieving the error in the above when using the following.  If I remove optional I receive the MutualAuthenticationError: Unable to authenticate <Response [302]> Any help appreciated.

    import requests
    from requests_kerberos import HTTPKerberosAuth, OPTIONAL

    kerberos_auth = HTTPKerberosAuth(mutual_authentication=OPTIONAL)

    proxies = {'http': 'http://proxy.company.org:8080',
           'https': 'http://proxy.company.org:8080',}
    
    #url =  'https://www.quandl.com/api/v3/datasets/WIKI/AAPL.json?collapse=daily?exclude_column_names=true'
   
    url =  'https://www.quandl.com/api/v3/databases/CLSM/data?api_key=<You will need a key from quandl>' 

    response = requests.get(url, proxies=proxies, verify='cert.pem', auth=kerberos_auth()) # what do I need to pass to the request param as the error denotes a missing positional param

**Comment by Lukasa** [comment]
Why are you calling `kerberos_auth()`? You should just pass it directly.

**Comment by toasteez** [comment]
Thanks, I was using their examples probably a typo on my part.  If I use:

    response = requests.get(url, proxies=proxies, verify='cert.pem', auth=HTTPKerberosAuth)

I get a proxy auth error 443...

Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required' 

Which is what I hoped the kerberos would resolve.

**Comment by Lukasa** [comment]
So you'd have to check what the actual auth header was coming back from the proxy. It's entirely possible that the proxy doesn't accept kerberos auth. To see that header you'll need to use a tool like tcpdump or wireshark.

**Comment by toasteez** [comment]
If I use:

    response = requests.get(url, proxies=proxies, verify='cert.pem', auth=HTTPKerberosAuth()) 

The error is:

    MutualAuthenticationError: Unable to authenticate <Response [302]>

**Comment by toasteez** [comment]
Would fiddler do it?

**Comment by Lukasa** [comment]
Probably not, because fiddler won't know how to forward on to your proxy.

**Comment by toasteez** [comment]
I'll attempt to get the tools.  which of two is preferable?

**Comment by Lukasa** [comment]
On Windows you'll have a much easier time with Wireshark: tcpdump can be tricky to run on Windows.

**Comment by rbcarson** [comment]
@toasteez If you got your original sample code elsewhere, then it looks like they intend to relax mutual authentication. Have you tried this:

```
response = requests.get(url, proxies=proxies, verify='cert.pem', auth=HTTPKerberosAuth(mutual_authentication=OPTIONAL)) 
```

**Comment by toasteez** [comment]
@Lukasa what do I need to filter for in Wireshark?

**Comment by Lukasa** [comment]
"host proxy.company.org and port 8080" should do it.

**Comment by toasteez** [comment]
@Lukasa is it the Hypertext Transfer Protocol I look at?  I can see a Proxy Authenticate and its NTLM not Kerberos.  I think the requests-ntlm implementation requires the user:pass so there is no real win there.

**Comment by Lukasa** [comment]
Yeah, that's right. If it's Proxy-Authenticate: NTLM then that's what you have to use.

**Comment by toasteez** [comment]
That is the same as passing the user:pass in the proxy dict or at environment level so what is the benefit of using requests-ntlm?

**Comment by Lukasa** [comment]
There is none. But is the proxy is telling you that's what you have to use, then that's what you have to use. BTW, what's the full value of the Proxy-Authenticate header?

**Comment by toasteez** [comment]
where do i see that?

**Comment by toasteez** [comment]
Proxy Authenticate is Negotiate, NTLM, Basic Realm=  "Squid ....."

**Comment by Lukasa** [comment]
Ok, so "Negotiate" is an unhelpful Windows name that allows Kerberos. So Kerberos should work.

**Comment by toasteez** [comment]
But if that is the case why does it deny and show NTLM? 

using response = requests.get(url, proxies=proxies, verify='cert.pem', auth=HTTPKerberosAuth(mutual_authentication=OPTIONAL))

**Comment by toasteez** [comment]
using 

   kerberos_auth = HTTPKerberosAuth(mutual_authentication=REQUIRED, sanitize_mutual_error_response=False)

    response = requests.get(url, proxies=proxies, verify='cert.pem', auth=kerberos_auth) 

Returns:
    MutualAuthenticationError: Unable to authenticate <Response [302]>

**Comment by Lukasa** [comment]
It doesn't deny, it's just failing to authenticate. That's a problem with requests-kerberos I assume.

**Comment by toasteez** [comment]
Yes - 
    requests_kerberos\kerberos_.py

**Comment by Lukasa** [comment]
So at this point I'm not really equipped to debug what's going on with your kerberos auth. It's just not something I understand or can replicate here.

**Comment by veklov** [comment]
@toasteez Hi, could you try HTTPSpnegoAuth from https://github.com/requests/requests-kerberos/pull/89 instead of HTTPKerberosAuth?

**Comment by jborean93** [comment]
Closing due to the age of the issue.
