### ISSUE TITLE
Install failed with GCC

### ISSUE THREAD

**Issue by landym** [requests/requests-kerberos#93]
I am attempting to do a pip install and I am getting a gcc error.  I am running on redhat linux.  Apparently gcc does not know that GSS_DLLIMP is defined and/or it is defined as empty. 

In file included from src/kerberosbasic.h:18:0, from src/kerberos.c:19:
/usr/include/gssapi/gssapi_generic.h:50:12: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'extern'
 GSS_DLLIMP extern gss_OID gss_nt_user_name;

I cannot figure out if this is a version of Kerberos (5), the krb5-devel package, or something else in the environment.  Any suggestions would be appreciated.

**Comment by behackett** [comment]
This isn't a requests-kerberos issue, but a build issue in pykerberos. You want to report it here: https://github.com/02strich/pykerberos.
