### ISSUE TITLE
GSSError: SSPI: InitializeSecurityContext: The specified target is unknown or unreachable

### ISSUE THREAD

**Issue by andrewpong** [requests/requests-kerberos#96]
With `0.11.0` (`requests == 2.14.2`, `winkerberos == 0.6.0`):

I'm receiving the following issue when trying to connect to a REST API on Windows - it works on MacOS, so it seems to be a change in how Kerberos requests are handled on Windows.

Can anyone shed light on why `generate_request_header()` is failing on `authGSSClientStep()`, with `GSSError: SSPI: InitializeSecurityContext: The specified target is unknown or unreachable`?

Is the specified target the host I'm trying to connect to, or the KDC? Is there more detail I can have returned?

```pycon
Unauthorized: Authorization denied - incorrect username or password.

In [3]: webapi = osisoftpy.webapi('https://dev.dstcontrols.com/piwebapi/', authtype=kerberos, verifyssl=False)
[kerberos_.py:188 handle_401() ] D handle_401(): Handling: 401
[kerberos_.py:146 generate_request_header() ] E generate_request_header(): authGSSClientStep() Failed:
Traceback (most recent call last):
  File "D:\venv\lib\site-packages\requests_kerberos\kerberos_.py", line 134, in generate_request_header negotiate_resp_ualue)
GSSError: SSPI: InitializeSecurityContext: The specified target is unknown or unreachable

[kerberos_.py:147 generate_request_header() ] E SSPI: InitializeSecurityContext: The specified target is unknown or unreachable
Traceback (most recent call last):
  File "D:\venv\lib\site-packages\requests_kerberos\kerberos_.py", line 134, in generate_request_header negotiate_resp_ualue)
GSSError: SSPI: InitializeSecurityContext: The specified target is unknown or unreachable

[kerberos_.py:191 handle_401() ] D handle_401(): returning <Response [401]>
[kerberos_.py:284 handle_response() ] D handle_response(): returning <Response [401]>
[kerberos_.py:285 handle_response() ] D handle_response() has seen 0 401 responses
[kerberos_.py:188 handle_401() ] D handle_401(): Handling: 401
[kerberos_.py:146 generate_request_header() ] E generate_request_header(): authGSSClientStep() Failed:
Traceback (most recent call last):
  File "D:\venv\lib\site-packages\requests_kerberos\kerberos_.py", line 134, in generate_request_header negotiate_resp_value)
GSSError: SSPI: InitializeSecurityContext: The specified target is unknown or unreachable

[kerberos_. :147 generate_request_header() ] E SSPI: InitializeSecurityContext: The specified target is unknown or unreachable
Traceback (most recent call last):
  File "D:\venv\lib\site-packages\requests_kerberos\kerberos_.py", 1ine 134, in generate_request_header negotiate_resp_value)
GSSError: SSPI: InitializeSecurityContext: The specified target is unknown or unreachable

[kerberos_.py:191 handle_401() ] D handle_401(): returning <Response [401]>
[kerberos_.py:284 handle_response() ] D handle_response(): returning <Response [401]>
[kerberos_.py:285 handle_response() ] D handle_response() has seen 1 401 responses
[kerberos_.py:291 handle_response() ] D handle_response(): returning 401 <Response [401]>
---------------------------------------------------------------------------
Unauthorized
Traceback (most recent call last)
<ipython-input-3-9446c733fd16>) in <module>()
----> 1 webapi = osisoftpy.webapi('https://dev.dstcontrols.com/piwebapi/', authtype='kerberos', verifyssl=False)

D:\venv\lib\site-packages\osisoftpy\api.pyc in webapi(url, authtype, username, password, verifyssl)
     66        r = APIResponse(s.get(url), s)
     67        if r.response.status_code == 401:
---> 68            raise Unauthorized('Authorization denied - incorrect username or password.')
     70        if r.response.status_code != 200:
     71            raise HTTPError('Wrong server response: %s %s' % (r.response.status_code, r.response.reason))

Unauthorized: Authorization denied - incorrect username or password.

In [4]: _
```

**Comment by behackett** [comment]
The error message comes directly from Microsoft's API. If I recall correctly, libkrb5 and heimdal use the FQDN of the host provided in the service principal for authentication, but SSPI does not. That's likely the difference.

**Comment by andrewpong** [comment]
Thanks for the quick response! I'll keep digging into how SSPI expects the host to be specified. Below are the variables that generate_request_header() had when it hit the error, FWIW.

```python
gssflags = {int} 10
host = {unicode} u'dev.dstcontrols.com'
is_preemptive = {bool} False
kerb_host = {unicode} u'api.osisoft.dstcontrols.local'
kerb_spn = {str} 'HTTP@api.osisoft.dstcontrols.local'
kerb_stage = {str} 'authGSSClientStep()'
negotiate_resp_value = {str} ''
response = {Response} <Response [401]>
result = {int} 1
self = {HTTPKerberosAuth} <requests_kerberos.kerberos_.HTTPKerberosAuth object at 0x0000000004393198>```

**Comment by behackett** [comment]
This is the behavior I mentioned:
https://web.mit.edu/kerberos/krb5-1.13/doc/admin/princ_dns.html#service-principal-canonicalization

I don't think SSPI does the same thing.

**Comment by TomFaulkner** [comment]
Was there resolution to this? I'm having the same issue.

I have tried overriding the host name with the fqdn of the url and with the results from dig, but either way I get the same result.

`[   DEBUG] - handle_401(): Handling: 401
[   ERROR] - generate_request_header(): authGSSClientStep() failed:
Traceback (most recent call last):
  File "C:\Users\AB14925\tabview_vsm_updates\lib\site-packages\requests_kerberos\kerberos_.py", line 134, in generate_request_header
    negotiate_resp_value)
winkerberos.GSSError: SSPI: InitializeSecurityContext: The specified target is unknown or unreachable

[   ERROR] - SSPI: InitializeSecurityContext: The specified target is unknown or unreachable
Traceback (most recent call last):
  File "C:\Users\AB14925\tabview_vsm_updates\lib\site-packages\requests_kerberos\kerberos_.py", line 134, in generate_request_header
    negotiate_resp_value)
winkerberos.GSSError: SSPI: InitializeSecurityContext: The specified target is unknown or unreachable

[   DEBUG] - handle_401(): returning <Response [401]>
[   DEBUG] - handle_response(): returning <Response [401]>
[   DEBUG] - handle_response() has seen 0 401 responses
[   DEBUG] - handle_401(): Handling: 401
[   ERROR] - generate_request_header(): authGSSClientStep() failed:
Traceback (most recent call last):
  File "C:\Users\AB14925\tabview_vsm_updates\lib\site-packages\requests_kerberos\kerberos_.py", line 134, in generate_request_header
    negotiate_resp_value)
winkerberos.GSSError: SSPI: InitializeSecurityContext: The specified target is unknown or unreachable

[   ERROR] - SSPI: InitializeSecurityContext: The specified target is unknown or unreachable
Traceback (most recent call last):
  File "C:\Users\AB14925\tabview_vsm_updates\lib\site-packages\requests_kerberos\kerberos_.py", line 134, in generate_request_header
    negotiate_resp_value)
winkerberos.GSSError: SSPI: InitializeSecurityContext: The specified target is unknown or unreachable

[   DEBUG] - handle_401(): returning <Response [401]>
[   DEBUG] - handle_response(): returning <Response [401]>
[   DEBUG] - handle_response() has seen 1 401 responses
[   DEBUG] - handle_response(): returning 401 <Response [401]>`

**Comment by batterseapower** [comment]
I'm hitting this issue too. I think requests-kerberos should use the FQDN: that's what Chrome does (https://github.com/adobe/chromium/blob/master/net/http/http_auth_handler_negotiate.cc#L128)

In python you can do this with socket.getfqdn('my-domain-name.com'). This can be supplied to the hostname_override param of HTTPKerberosAuth as a workaround until requests-kerberos is fixed.

**Comment by behackett** [comment]
I'm not convinced socket.getfqdn is what you want. The C code that krb5 uses is here:

https://github.com/krb5/krb5/blob/9c18f6c93b602ec69ca2640e27ab2ccbb7f45a3c/src/lib/krb5/os/sn2princ.c#L68-L87

The Python equivalent is here:

https://github.com/krb5/krb5/blob/d406afa363554097ac48646a29249c04f498c88e/src/util/k5test.py#L505-L520

**Comment by batterseapower** [comment]
@behackett OK, I've updated #108 accordingly. k5test used socket.getnameinfo to resolve the socketaddr to a name but in my testing this was slow & always failed so I'm skipping that step. Doesn't seem to have any adverse consequences that I can see.

**Comment by orcahmlee** [comment]
@andrewpong Hi, Andrew. This is my first time using [pi_web_api_client](https://github.com/osimloeff/PI-Web-API-Client-Python) to connect the PI-Server. 
```
client = PIWebApiClient(
    baseUrl=baseUrl, 
    useKerberos=True, 
    username=username, 
    password=password, 
    verifySsl=False
)
client.home.get()
```

I also got the GSSError when I tried to connect PI-Server on Windows. I saw your comment said that this error would be received on Windows but it works on MacOS. <br>
May I ask which path should I put the CA on MacOS/Linux when I try to connect PI-Server? 

```
---------------------------------------------------------------------------
GSSError                                  Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\requests_kerberos\kerberos_.py in generate_request_header(self, response, host, is_preemptive)
    229                 result = kerberos.authGSSClientStep(self.context[host],
--> 230                                                     negotiate_resp_value)
    231 

GSSError: SSPI: InitializeSecurityContext: �����εL�k�F�쪺���w�ؼ�


During handling of the above exception, another exception occurred:

KerberosExchangeError                     Traceback (most recent call last)
<ipython-input-9-4cdf084fd628> in <module>()
      1 # Get the home infomation of the client
----> 2 client.home.get()

C:\ProgramData\Anaconda3\lib\site-packages\osisoft\pidevclub\piwebapi\api\home_api.py in get(self, **kwargs)
     27                         return self.get_with_http_info(**kwargs)
     28                 else:
---> 29                         (data) = self.get_with_http_info(**kwargs)
     30                         return data
     31 

C:\ProgramData\Anaconda3\lib\site-packages\osisoft\pidevclub\piwebapi\api\home_api.py in get_with_http_info(self, **kwargs)
     80                                 _preload_content =params.get('_preload_content', True),
     81                                 _request_timeout=params.get('_request_timeout'),
---> 82 				collection_formats =collection_formats)
     83 

C:\ProgramData\Anaconda3\lib\site-packages\osisoft\pidevclub\piwebapi\api_client.py in call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, callback, _return_http_data_only, collection_formats, _preload_content, _request_timeout)
    309                                    body, post_params, files,
    310                                    response_type, callback,
--> 311                                    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
    312         else:
    313             thread = threading.Thread(target=self.__call_api,

C:\ProgramData\Anaconda3\lib\site-packages\osisoft\pidevclub\piwebapi\api_client.py in __call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, callback, _return_http_data_only, collection_formats, _preload_content, _request_timeout)
    137                                      query_params=query_params,
    138                                      headers=header_params,
--> 139                                      body=body)
    140 
    141         return_data = response_data

C:\ProgramData\Anaconda3\lib\site-packages\osisoft\pidevclub\piwebapi\api_client.py in request(self, method, url, query_params, headers, body)
    327                                     body=body,
    328                                     query_params=query_params,
--> 329                                     headers=headers)
    330 
    331 

C:\ProgramData\Anaconda3\lib\site-packages\osisoft\pidevclub\piwebapi\rest.py in send_request(self, url, method, body, headers, query_params)
     55 
     56         if method == "GET":
---> 57             response = requests.get(url, auth=self.auth, headers=headers, verify=self.verifySsl)
     58         elif method == "HEAD":
     59             response = requests.head(url, auth=self.auth, headers=headers, verify=self.verifySsl)

C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py in get(url, params, **kwargs)
     70 
     71     kwargs.setdefault('allow_redirects', True)
---> 72     return request('get', url, params=params, **kwargs)
     73 
     74 

C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py in request(method, url, **kwargs)
     56     # cases, and look like a memory leak in others.
     57     with sessions.Session() as session:
---> 58         return session.request(method=method, url=url, **kwargs)
     59 
     60 

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    496             hooks=hooks,
    497         )
--> 498         prep = self.prepare_request(req)
    499 
    500         proxies = proxies or {}

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in prepare_request(self, request)
    439             auth=merge_setting(auth, self.auth),
    440             cookies=merged_cookies,
--> 441             hooks=merge_hooks(request.hooks, self.hooks),
    442         )
    443         return p

C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py in prepare(self, method, url, headers, files, data, params, auth, cookies, hooks, json)
    311         self.prepare_cookies(cookies)
    312         self.prepare_body(data, files, json)
--> 313         self.prepare_auth(auth, url)
    314 
    315         # Note that prepare_auth must be last to enable authentication schemes

C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py in prepare_auth(self, auth, url)
    542 
    543             # Allow auth to make its changes.
--> 544             r = auth(self)
    545 
    546             # Update self to reflect the auth changes.

C:\ProgramData\Anaconda3\lib\site-packages\requests_kerberos\kerberos_.py in __call__(self, request)
    435             host = urlparse(request.url).hostname
    436 
--> 437             auth_header = self.generate_request_header(None, host, is_preemptive=True)
    438 
    439             log.debug("HTTPKerberosAuth: Preemptive Authorization header: {0}".format(auth_header))

C:\ProgramData\Anaconda3\lib\site-packages\requests_kerberos\kerberos_.py in generate_request_header(self, response, host, is_preemptive)
    242                 "generate_request_header(): {0} failed:".format(kerb_stage))
    243             log.exception(error)
--> 244             raise KerberosExchangeError("%s failed: %s" % (kerb_stage, str(error.args)))
    245 
    246         except EnvironmentError as error:

KerberosExchangeError: authGSSClientStep() failed: ('SSPI: InitializeSecurityContext: �����εL�k�F�쪺���w�ؼ�\r\n',)
```

**Comment by eddyrene** [comment]
> @andrewpong Hi, Andrew. This is my first time using pi_web_api_client to connect the PI-Server.
> client = PIWebApiClient(
>     baseUrl=baseUrl, 
>     useKerberos=True, 
>     username=username, 
>     password=password, 
>     verifySsl=False
> )
> client.home.get()
> 
> I also got the GSSError when I tried to connect PI-Server on Windows. I saw your comment said that this error would be received on Windows but it works on MacOS. 
> May I ask which path should I put the CA on MacOS/Linux when I try to connect PI-Server?
> ---------------------------------------------------------------------------
> GSSError                                  Traceback (most recent call last)
> C:\ProgramData\Anaconda3\lib\site-packages\requests_kerberos\kerberos_.py in generate_request_header(self, response, host, is_preemptive)
>     229                 result = kerberos.authGSSClientStep(self.context[host],
> --> 230                                                     negotiate_resp_value)
>     231 
> 
> GSSError: SSPI: InitializeSecurityContext: �����εL�k�F�쪺���w�ؼ�
> 
> 
> During handling of the above exception, another exception occurred:
> 
> KerberosExchangeError                     Traceback (most recent call last)
> <ipython-input-9-4cdf084fd628> in <module>()
>       1 # Get the home infomation of the client
> ----> 2 client.home.get()
> 
> C:\ProgramData\Anaconda3\lib\site-packages\osisoft\pidevclub\piwebapi\api\home_api.py in get(self, **kwargs)
>      27                         return self.get_with_http_info(**kwargs)
>      28                 else:
> ---> 29                         (data) = self.get_with_http_info(**kwargs)
>      30                         return data
>      31 
> 
> C:\ProgramData\Anaconda3\lib\site-packages\osisoft\pidevclub\piwebapi\api\home_api.py in get_with_http_info(self, **kwargs)
>      80                                 _preload_content =params.get('_preload_content', True),
>      81                                 _request_timeout=params.get('_request_timeout'),
> ---> 82 				collection_formats =collection_formats)
>      83 
> 
> C:\ProgramData\Anaconda3\lib\site-packages\osisoft\pidevclub\piwebapi\api_client.py in call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, callback, _return_http_data_only, collection_formats, _preload_content, _request_timeout)
>     309                                    body, post_params, files,
>     310                                    response_type, callback,
> --> 311                                    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
>     312         else:
>     313             thread = threading.Thread(target=self.__call_api,
> 
> C:\ProgramData\Anaconda3\lib\site-packages\osisoft\pidevclub\piwebapi\api_client.py in __call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, callback, _return_http_data_only, collection_formats, _preload_content, _request_timeout)
>     137                                      query_params=query_params,
>     138                                      headers=header_params,
> --> 139                                      body=body)
>     140 
>     141         return_data = response_data
> 
> C:\ProgramData\Anaconda3\lib\site-packages\osisoft\pidevclub\piwebapi\api_client.py in request(self, method, url, query_params, headers, body)
>     327                                     body=body,
>     328                                     query_params=query_params,
> --> 329                                     headers=headers)
>     330 
>     331 
> 
> C:\ProgramData\Anaconda3\lib\site-packages\osisoft\pidevclub\piwebapi\rest.py in send_request(self, url, method, body, headers, query_params)
>      55 
>      56         if method == "GET":
> ---> 57             response = requests.get(url, auth=self.auth, headers=headers, verify=self.verifySsl)
>      58         elif method == "HEAD":
>      59             response = requests.head(url, auth=self.auth, headers=headers, verify=self.verifySsl)
> 
> C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py in get(url, params, **kwargs)
>      70 
>      71     kwargs.setdefault('allow_redirects', True)
> ---> 72     return request('get', url, params=params, **kwargs)
>      73 
>      74 
> 
> C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py in request(method, url, **kwargs)
>      56     # cases, and look like a memory leak in others.
>      57     with sessions.Session() as session:
> ---> 58         return session.request(method=method, url=url, **kwargs)
>      59 
>      60 
> 
> C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
>     496             hooks=hooks,
>     497         )
> --> 498         prep = self.prepare_request(req)
>     499 
>     500         proxies = proxies or {}
> 
> C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in prepare_request(self, request)
>     439             auth=merge_setting(auth, self.auth),
>     440             cookies=merged_cookies,
> --> 441             hooks=merge_hooks(request.hooks, self.hooks),
>     442         )
>     443         return p
> 
> C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py in prepare(self, method, url, headers, files, data, params, auth, cookies, hooks, json)
>     311         self.prepare_cookies(cookies)
>     312         self.prepare_body(data, files, json)
> --> 313         self.prepare_auth(auth, url)
>     314 
>     315         # Note that prepare_auth must be last to enable authentication schemes
> 
> C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py in prepare_auth(self, auth, url)
>     542 
>     543             # Allow auth to make its changes.
> --> 544             r = auth(self)
>     545 
>     546             # Update self to reflect the auth changes.
> 
> C:\ProgramData\Anaconda3\lib\site-packages\requests_kerberos\kerberos_.py in __call__(self, request)
>     435             host = urlparse(request.url).hostname
>     436 
> --> 437             auth_header = self.generate_request_header(None, host, is_preemptive=True)
>     438 
>     439             log.debug("HTTPKerberosAuth: Preemptive Authorization header: {0}".format(auth_header))
> 
> C:\ProgramData\Anaconda3\lib\site-packages\requests_kerberos\kerberos_.py in generate_request_header(self, response, host, is_preemptive)
>     242                 "generate_request_header(): {0} failed:".format(kerb_stage))
>     243             log.exception(error)
> --> 244             raise KerberosExchangeError("%s failed: %s" % (kerb_stage, str(error.args)))
>     245 
>     246         except EnvironmentError as error:
> 
> KerberosExchangeError: authGSSClientStep() failed: ('SSPI: InitializeSecurityContext: �����εL�k�F�쪺���w�ؼ�\r\n',)

Same problem, could you resolve?

**Comment by jborean93** [comment]
Closing as this error indicates the target host specified in the SPN is does not match anything found in the domain. You will have to ensure the service and hostname used match what SPN the target has been registered against. This can fail in many ways if you are connecting using a hostname that is not the actual hostname in question. As a side note Heimdal/MIT have code to automatically do a reverse DNS resolution of the target SPN host which could indicate why things work on macOS (Heimdal) but not Windows.
