### ISSUE TITLE
Python kerberos library selection 

### ISSUE THREAD

**Issue by nitzmahone** [requests/requests-kerberos#97]
With the `pykerberos` fork effectively going dark (see discussion at https://github.com/02strich/pykerberos/pull/27) and Apple's original ccs-pykerberos being apparently erstwhile maintained, I'm wondering what we can do to be on a supported Kerberos layer that's being actively maintained? pywinrm has a need to merge some specific IOV wrapping code that can only be implemented with low-level access to the C library and structures- we've got the code written, but Apple appears to have gone dark again (even if I could get the changes merged, I have no confidence that we could get any future bugfixes merged/released quickly). One option might be https://github.com/pythongssapi/python-gssapi - it uses Cython to provide access to both a high-level API and the underlying C API, so we could actually reimplement what we have in pure Python if this library were used. Biggest problem I can see there would be the Windows stuff that's mirroring the pykerberos library- we'd have to effectively split the implementation or write an interposer that would mimic the pykerberos API (since AFAIK there's no Windows equivalent available). We could also of course just make yet another fork of the original ccs-pykerberos...

We might (at least temporarily) take the gssapi approach with pywinrm and vendor a hacked requests-kerberos inside it, as that frees us from the reliance on third parties to get bugs fixed and released, but I'm curious if the requests team has any thoughts or different ideas about this problem in general?

**Comment by nitzmahone** [comment]
(kept meaning to hassle @Lukasa at Pycon about this but forgot)

**Comment by Lukasa** [comment]
Honestly, I think we don't have an opinion on this as a team. Generally speaking I think our position on this is that we want to use an actively maintained Kerberos implementation if we can, and we also don't want to be jumping around between implementations. 

So far we haven't managed to do that very well: I'd like to find a way to do better. Sadly, I have no concrete advice as to what to do here: this is just not a space I know much about.

**Comment by 02strich** [comment]
@nitzmahone has apple come back on your pull requests regarding the additional IOV features? At this point, what is the level of confidence that apple will keep maintaining upstream?

**Comment by behackett** [comment]
I don't see a pull request for ccs-pykerberos to add the IOV wrapping code. Did they previously reject it?

**Comment by nitzmahone** [comment]
After the radio silence on other open PRs, I hadn't made one for this- I'd settled on the strategy of repackaging it as a standalone project. But then they came back out of the woodwork and merged things after a couple months, and we started engaging with them on IRC. They're open to merging the IOV stuff so long as it doesn't destabilize things. I've also gained maintainer access to Github and PyPI for pykerberos this week (thanks @02strich!), so once we get past Ansible's code freeze next week, I'll be re-repackaging it and releasing it in pykerberos, as well as PRing to ccs-pykerberos. Once it's merged and released there, we're probably "hollow out" pykerberos and just make it an empty package that depends on the latest version of ccs-pykerberos. That leaves us the option to re-fork (even temporarily) if Apple goes dark or can't ship things quickly enough. I could see us leaving it that way indefinitely, really- only downside is that requests-kerberos wouldn't be able to require a minimum version of ccs-pykerberos transitively (though we could even address that with a simple version update of pykerberos that had a `>=` dep).

**Comment by behackett** [comment]
Excellent! Thanks for the update. Making pykerberos depend on ccs-pykerberos solves a number of problems.

**Comment by nitzmahone** [comment]
Yeah, the only nasty bit I can think of is if we end up needing to re-fork down the line, as then you'd have "live" versions of pykeberos and ccs-pykerberos installed at the same time. My Python-fu isn't strong enough to know off the top of my head how it resolves that problem (since both implement the `kerberos` module), but I know it's problematic. I guess worst case maybe we could do some inspection in a customized setup,py in pykerberos that could abort the installation and/or say, "don't do that".

**Comment by 02strich** [comment]
we had discussed this point in a pykerberos issue as well and there is no super clean way out of it that I am aware of. One idea that I still like is renaming the pykerberos module while providing some shim layer, e.g. while pykerberos is just a shim it still has a pykerberos module which just imports the kerberos-ccs module. When a re-fork becomes necessary this gives a hook point. In the medium term this means that users should migrate to a different module name (but would not be broken) but future-proofs the setup.

**Comment by jmehnle** [comment]
So has a decision been made? Will `requests-kerberos` keep depending on `pykerberos` as opposed to Apple's `kerberos` module?

**Comment by jborean93** [comment]
Closing as https://github.com/requests/requests-kerberos/pull/163 has changed the underlying Kerberos library away from both pykerberos and ccs-pykerberos due to their age and ease of use in the newer libraries.
